// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CockroachSql
{
    public static class GetSequences
    {
        public static Task<GetSequencesResult> InvokeAsync(GetSequencesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSequencesResult>("cockroachsql:index/getSequences:getSequences", args ?? new GetSequencesArgs(), options.WithDefaults());

        public static Output<GetSequencesResult> Invoke(GetSequencesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSequencesResult>("cockroachsql:index/getSequences:getSequences", args ?? new GetSequencesInvokeArgs(), options.WithDefaults());

        public static Output<GetSequencesResult> Invoke(GetSequencesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSequencesResult>("cockroachsql:index/getSequences:getSequences", args ?? new GetSequencesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSequencesArgs : global::Pulumi.InvokeArgs
    {
        [Input("database", required: true)]
        public string Database { get; set; } = null!;

        [Input("likeAllPatterns")]
        private List<string>? _likeAllPatterns;
        public List<string> LikeAllPatterns
        {
            get => _likeAllPatterns ?? (_likeAllPatterns = new List<string>());
            set => _likeAllPatterns = value;
        }

        [Input("likeAnyPatterns")]
        private List<string>? _likeAnyPatterns;
        public List<string> LikeAnyPatterns
        {
            get => _likeAnyPatterns ?? (_likeAnyPatterns = new List<string>());
            set => _likeAnyPatterns = value;
        }

        [Input("notLikeAllPatterns")]
        private List<string>? _notLikeAllPatterns;
        public List<string> NotLikeAllPatterns
        {
            get => _notLikeAllPatterns ?? (_notLikeAllPatterns = new List<string>());
            set => _notLikeAllPatterns = value;
        }

        [Input("regexPattern")]
        public string? RegexPattern { get; set; }

        [Input("schemas")]
        private List<string>? _schemas;
        public List<string> Schemas
        {
            get => _schemas ?? (_schemas = new List<string>());
            set => _schemas = value;
        }

        public GetSequencesArgs()
        {
        }
        public static new GetSequencesArgs Empty => new GetSequencesArgs();
    }

    public sealed class GetSequencesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("database", required: true)]
        public Input<string> Database { get; set; } = null!;

        [Input("likeAllPatterns")]
        private InputList<string>? _likeAllPatterns;
        public InputList<string> LikeAllPatterns
        {
            get => _likeAllPatterns ?? (_likeAllPatterns = new InputList<string>());
            set => _likeAllPatterns = value;
        }

        [Input("likeAnyPatterns")]
        private InputList<string>? _likeAnyPatterns;
        public InputList<string> LikeAnyPatterns
        {
            get => _likeAnyPatterns ?? (_likeAnyPatterns = new InputList<string>());
            set => _likeAnyPatterns = value;
        }

        [Input("notLikeAllPatterns")]
        private InputList<string>? _notLikeAllPatterns;
        public InputList<string> NotLikeAllPatterns
        {
            get => _notLikeAllPatterns ?? (_notLikeAllPatterns = new InputList<string>());
            set => _notLikeAllPatterns = value;
        }

        [Input("regexPattern")]
        public Input<string>? RegexPattern { get; set; }

        [Input("schemas")]
        private InputList<string>? _schemas;
        public InputList<string> Schemas
        {
            get => _schemas ?? (_schemas = new InputList<string>());
            set => _schemas = value;
        }

        public GetSequencesInvokeArgs()
        {
        }
        public static new GetSequencesInvokeArgs Empty => new GetSequencesInvokeArgs();
    }


    [OutputType]
    public sealed class GetSequencesResult
    {
        public readonly string Database;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> LikeAllPatterns;
        public readonly ImmutableArray<string> LikeAnyPatterns;
        public readonly ImmutableArray<string> NotLikeAllPatterns;
        public readonly string? RegexPattern;
        public readonly ImmutableArray<string> Schemas;
        public readonly ImmutableArray<Outputs.GetSequencesSequenceResult> Sequences;

        [OutputConstructor]
        private GetSequencesResult(
            string database,

            string id,

            ImmutableArray<string> likeAllPatterns,

            ImmutableArray<string> likeAnyPatterns,

            ImmutableArray<string> notLikeAllPatterns,

            string? regexPattern,

            ImmutableArray<string> schemas,

            ImmutableArray<Outputs.GetSequencesSequenceResult> sequences)
        {
            Database = database;
            Id = id;
            LikeAllPatterns = likeAllPatterns;
            LikeAnyPatterns = likeAnyPatterns;
            NotLikeAllPatterns = notLikeAllPatterns;
            RegexPattern = regexPattern;
            Schemas = schemas;
            Sequences = sequences;
        }
    }
}
