// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CockroachSql
{
    public static class GetTables
    {
        public static Task<GetTablesResult> InvokeAsync(GetTablesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTablesResult>("cockroachsql:index/getTables:getTables", args ?? new GetTablesArgs(), options.WithDefaults());

        public static Output<GetTablesResult> Invoke(GetTablesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTablesResult>("cockroachsql:index/getTables:getTables", args ?? new GetTablesInvokeArgs(), options.WithDefaults());

        public static Output<GetTablesResult> Invoke(GetTablesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTablesResult>("cockroachsql:index/getTables:getTables", args ?? new GetTablesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTablesArgs : global::Pulumi.InvokeArgs
    {
        [Input("database", required: true)]
        public string Database { get; set; } = null!;

        [Input("likeAllPatterns")]
        private List<string>? _likeAllPatterns;
        public List<string> LikeAllPatterns
        {
            get => _likeAllPatterns ?? (_likeAllPatterns = new List<string>());
            set => _likeAllPatterns = value;
        }

        [Input("likeAnyPatterns")]
        private List<string>? _likeAnyPatterns;
        public List<string> LikeAnyPatterns
        {
            get => _likeAnyPatterns ?? (_likeAnyPatterns = new List<string>());
            set => _likeAnyPatterns = value;
        }

        [Input("notLikeAllPatterns")]
        private List<string>? _notLikeAllPatterns;
        public List<string> NotLikeAllPatterns
        {
            get => _notLikeAllPatterns ?? (_notLikeAllPatterns = new List<string>());
            set => _notLikeAllPatterns = value;
        }

        [Input("regexPattern")]
        public string? RegexPattern { get; set; }

        [Input("schemas")]
        private List<string>? _schemas;
        public List<string> Schemas
        {
            get => _schemas ?? (_schemas = new List<string>());
            set => _schemas = value;
        }

        [Input("tableTypes")]
        private List<string>? _tableTypes;
        public List<string> TableTypes
        {
            get => _tableTypes ?? (_tableTypes = new List<string>());
            set => _tableTypes = value;
        }

        public GetTablesArgs()
        {
        }
        public static new GetTablesArgs Empty => new GetTablesArgs();
    }

    public sealed class GetTablesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("database", required: true)]
        public Input<string> Database { get; set; } = null!;

        [Input("likeAllPatterns")]
        private InputList<string>? _likeAllPatterns;
        public InputList<string> LikeAllPatterns
        {
            get => _likeAllPatterns ?? (_likeAllPatterns = new InputList<string>());
            set => _likeAllPatterns = value;
        }

        [Input("likeAnyPatterns")]
        private InputList<string>? _likeAnyPatterns;
        public InputList<string> LikeAnyPatterns
        {
            get => _likeAnyPatterns ?? (_likeAnyPatterns = new InputList<string>());
            set => _likeAnyPatterns = value;
        }

        [Input("notLikeAllPatterns")]
        private InputList<string>? _notLikeAllPatterns;
        public InputList<string> NotLikeAllPatterns
        {
            get => _notLikeAllPatterns ?? (_notLikeAllPatterns = new InputList<string>());
            set => _notLikeAllPatterns = value;
        }

        [Input("regexPattern")]
        public Input<string>? RegexPattern { get; set; }

        [Input("schemas")]
        private InputList<string>? _schemas;
        public InputList<string> Schemas
        {
            get => _schemas ?? (_schemas = new InputList<string>());
            set => _schemas = value;
        }

        [Input("tableTypes")]
        private InputList<string>? _tableTypes;
        public InputList<string> TableTypes
        {
            get => _tableTypes ?? (_tableTypes = new InputList<string>());
            set => _tableTypes = value;
        }

        public GetTablesInvokeArgs()
        {
        }
        public static new GetTablesInvokeArgs Empty => new GetTablesInvokeArgs();
    }


    [OutputType]
    public sealed class GetTablesResult
    {
        public readonly string Database;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> LikeAllPatterns;
        public readonly ImmutableArray<string> LikeAnyPatterns;
        public readonly ImmutableArray<string> NotLikeAllPatterns;
        public readonly string? RegexPattern;
        public readonly ImmutableArray<string> Schemas;
        public readonly ImmutableArray<string> TableTypes;
        public readonly ImmutableArray<Outputs.GetTablesTableResult> Tables;

        [OutputConstructor]
        private GetTablesResult(
            string database,

            string id,

            ImmutableArray<string> likeAllPatterns,

            ImmutableArray<string> likeAnyPatterns,

            ImmutableArray<string> notLikeAllPatterns,

            string? regexPattern,

            ImmutableArray<string> schemas,

            ImmutableArray<string> tableTypes,

            ImmutableArray<Outputs.GetTablesTableResult> tables)
        {
            Database = database;
            Id = id;
            LikeAllPatterns = likeAllPatterns;
            LikeAnyPatterns = likeAnyPatterns;
            NotLikeAllPatterns = notLikeAllPatterns;
            RegexPattern = regexPattern;
            Schemas = schemas;
            TableTypes = tableTypes;
            Tables = tables;
        }
    }
}
