// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CockroachSql
{
    [CockroachSqlResourceType("cockroachsql:index/grantRole:GrantRole")]
    public partial class GrantRole : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the role that is granted to role
        /// </summary>
        [Output("grantRole")]
        public Output<string> GrantRoleName { get; private set; } = null!;

        /// <summary>
        /// The name of the role to grant grant_role
        /// </summary>
        [Output("role")]
        public Output<string> Role { get; private set; } = null!;

        /// <summary>
        /// Permit the grant recipient to grant it to others
        /// </summary>
        [Output("withAdminOption")]
        public Output<bool?> WithAdminOption { get; private set; } = null!;


        /// <summary>
        /// Create a GrantRole resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public GrantRole(string name, GrantRoleArgs args, CustomResourceOptions? options = null)
            : base("cockroachsql:index/grantRole:GrantRole", name, args ?? new GrantRoleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private GrantRole(string name, Input<string> id, GrantRoleState? state = null, CustomResourceOptions? options = null)
            : base("cockroachsql:index/grantRole:GrantRole", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/nellisauction/pulumi-cockroachsql",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing GrantRole resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static GrantRole Get(string name, Input<string> id, GrantRoleState? state = null, CustomResourceOptions? options = null)
        {
            return new GrantRole(name, id, state, options);
        }
    }

    public sealed class GrantRoleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the role that is granted to role
        /// </summary>
        [Input("grantRole", required: true)]
        public Input<string> GrantRoleName { get; set; } = null!;

        /// <summary>
        /// The name of the role to grant grant_role
        /// </summary>
        [Input("role", required: true)]
        public Input<string> Role { get; set; } = null!;

        /// <summary>
        /// Permit the grant recipient to grant it to others
        /// </summary>
        [Input("withAdminOption")]
        public Input<bool>? WithAdminOption { get; set; }

        public GrantRoleArgs()
        {
        }
        public static new GrantRoleArgs Empty => new GrantRoleArgs();
    }

    public sealed class GrantRoleState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the role that is granted to role
        /// </summary>
        [Input("grantRole")]
        public Input<string>? GrantRoleName { get; set; }

        /// <summary>
        /// The name of the role to grant grant_role
        /// </summary>
        [Input("role")]
        public Input<string>? Role { get; set; }

        /// <summary>
        /// Permit the grant recipient to grant it to others
        /// </summary>
        [Input("withAdminOption")]
        public Input<bool>? WithAdminOption { get; set; }

        public GrantRoleState()
        {
        }
        public static new GrantRoleState Empty => new GrantRoleState();
    }
}
