// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CockroachSql
{
    [CockroachSqlResourceType("cockroachsql:index/role:Role")]
    public partial class Role : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Determine whether this role will be permitted to create new roles
        /// </summary>
        [Output("createRole")]
        public Output<bool?> CreateRole { get; private set; } = null!;

        [Output("encrypted")]
        public Output<string?> Encrypted { get; private set; } = null!;

        /// <summary>
        /// Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
        /// </summary>
        [Output("idleInTransactionSessionTimeout")]
        public Output<int?> IdleInTransactionSessionTimeout { get; private set; } = null!;

        /// <summary>
        /// Determine whether a role is allowed to log in
        /// </summary>
        [Output("login")]
        public Output<bool?> Login { get; private set; } = null!;

        /// <summary>
        /// The name of the role
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Sets the role's password
        /// </summary>
        [Output("password")]
        public Output<string?> Password { get; private set; } = null!;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Sets the role's password without storing it in the state file.
        /// </summary>
        [Output("passwordWo")]
        public Output<string?> PasswordWo { get; private set; } = null!;

        /// <summary>
        /// Prevents applies from updating the role password on every apply unless the value changes.
        /// </summary>
        [Output("passwordWoVersion")]
        public Output<string?> PasswordWoVersion { get; private set; } = null!;

        /// <summary>
        /// Role(s) to grant to this new role
        /// </summary>
        [Output("roles")]
        public Output<ImmutableArray<string>> Roles { get; private set; } = null!;

        /// <summary>
        /// Sets the role's search path
        /// </summary>
        [Output("searchPaths")]
        public Output<ImmutableArray<string>> SearchPaths { get; private set; } = null!;

        /// <summary>
        /// Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
        /// </summary>
        [Output("skipDropRole")]
        public Output<bool?> SkipDropRole { get; private set; } = null!;

        /// <summary>
        /// Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
        /// </summary>
        [Output("skipReassignOwned")]
        public Output<bool?> SkipReassignOwned { get; private set; } = null!;

        /// <summary>
        /// Abort any statement that takes more than the specified number of milliseconds
        /// </summary>
        [Output("statementTimeout")]
        public Output<int?> StatementTimeout { get; private set; } = null!;

        /// <summary>
        /// Sets a date and time after which the role's password is no longer valid
        /// </summary>
        [Output("validUntil")]
        public Output<string?> ValidUntil { get; private set; } = null!;


        /// <summary>
        /// Create a Role resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Role(string name, RoleArgs? args = null, CustomResourceOptions? options = null)
            : base("cockroachsql:index/role:Role", name, args ?? new RoleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Role(string name, Input<string> id, RoleState? state = null, CustomResourceOptions? options = null)
            : base("cockroachsql:index/role:Role", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/nellisauction/pulumi-cockroachsql",
                AdditionalSecretOutputs =
                {
                    "password",
                    "passwordWo",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Role resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Role Get(string name, Input<string> id, RoleState? state = null, CustomResourceOptions? options = null)
        {
            return new Role(name, id, state, options);
        }
    }

    public sealed class RoleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Determine whether this role will be permitted to create new roles
        /// </summary>
        [Input("createRole")]
        public Input<bool>? CreateRole { get; set; }

        [Input("encrypted")]
        public Input<string>? Encrypted { get; set; }

        /// <summary>
        /// Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
        /// </summary>
        [Input("idleInTransactionSessionTimeout")]
        public Input<int>? IdleInTransactionSessionTimeout { get; set; }

        /// <summary>
        /// Determine whether a role is allowed to log in
        /// </summary>
        [Input("login")]
        public Input<bool>? Login { get; set; }

        /// <summary>
        /// The name of the role
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// Sets the role's password
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("passwordWo")]
        private Input<string>? _passwordWo;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Sets the role's password without storing it in the state file.
        /// </summary>
        public Input<string>? PasswordWo
        {
            get => _passwordWo;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _passwordWo = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Prevents applies from updating the role password on every apply unless the value changes.
        /// </summary>
        [Input("passwordWoVersion")]
        public Input<string>? PasswordWoVersion { get; set; }

        [Input("roles")]
        private InputList<string>? _roles;

        /// <summary>
        /// Role(s) to grant to this new role
        /// </summary>
        public InputList<string> Roles
        {
            get => _roles ?? (_roles = new InputList<string>());
            set => _roles = value;
        }

        [Input("searchPaths")]
        private InputList<string>? _searchPaths;

        /// <summary>
        /// Sets the role's search path
        /// </summary>
        public InputList<string> SearchPaths
        {
            get => _searchPaths ?? (_searchPaths = new InputList<string>());
            set => _searchPaths = value;
        }

        /// <summary>
        /// Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
        /// </summary>
        [Input("skipDropRole")]
        public Input<bool>? SkipDropRole { get; set; }

        /// <summary>
        /// Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
        /// </summary>
        [Input("skipReassignOwned")]
        public Input<bool>? SkipReassignOwned { get; set; }

        /// <summary>
        /// Abort any statement that takes more than the specified number of milliseconds
        /// </summary>
        [Input("statementTimeout")]
        public Input<int>? StatementTimeout { get; set; }

        /// <summary>
        /// Sets a date and time after which the role's password is no longer valid
        /// </summary>
        [Input("validUntil")]
        public Input<string>? ValidUntil { get; set; }

        public RoleArgs()
        {
        }
        public static new RoleArgs Empty => new RoleArgs();
    }

    public sealed class RoleState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Determine whether this role will be permitted to create new roles
        /// </summary>
        [Input("createRole")]
        public Input<bool>? CreateRole { get; set; }

        [Input("encrypted")]
        public Input<string>? Encrypted { get; set; }

        /// <summary>
        /// Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
        /// </summary>
        [Input("idleInTransactionSessionTimeout")]
        public Input<int>? IdleInTransactionSessionTimeout { get; set; }

        /// <summary>
        /// Determine whether a role is allowed to log in
        /// </summary>
        [Input("login")]
        public Input<bool>? Login { get; set; }

        /// <summary>
        /// The name of the role
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// Sets the role's password
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("passwordWo")]
        private Input<string>? _passwordWo;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Sets the role's password without storing it in the state file.
        /// </summary>
        public Input<string>? PasswordWo
        {
            get => _passwordWo;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _passwordWo = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Prevents applies from updating the role password on every apply unless the value changes.
        /// </summary>
        [Input("passwordWoVersion")]
        public Input<string>? PasswordWoVersion { get; set; }

        [Input("roles")]
        private InputList<string>? _roles;

        /// <summary>
        /// Role(s) to grant to this new role
        /// </summary>
        public InputList<string> Roles
        {
            get => _roles ?? (_roles = new InputList<string>());
            set => _roles = value;
        }

        [Input("searchPaths")]
        private InputList<string>? _searchPaths;

        /// <summary>
        /// Sets the role's search path
        /// </summary>
        public InputList<string> SearchPaths
        {
            get => _searchPaths ?? (_searchPaths = new InputList<string>());
            set => _searchPaths = value;
        }

        /// <summary>
        /// Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
        /// </summary>
        [Input("skipDropRole")]
        public Input<bool>? SkipDropRole { get; set; }

        /// <summary>
        /// Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
        /// </summary>
        [Input("skipReassignOwned")]
        public Input<bool>? SkipReassignOwned { get; set; }

        /// <summary>
        /// Abort any statement that takes more than the specified number of milliseconds
        /// </summary>
        [Input("statementTimeout")]
        public Input<int>? StatementTimeout { get; set; }

        /// <summary>
        /// Sets a date and time after which the role's password is no longer valid
        /// </summary>
        [Input("validUntil")]
        public Input<string>? ValidUntil { get; set; }

        public RoleState()
        {
        }
        public static new RoleState Empty => new RoleState();
    }
}
