// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/nellisauction/pulumi-cockroachsql/sdk/go/cockroachsql/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// SSL client certificate if required by the database.
func GetClientcert(ctx *pulumi.Context) string {
	return config.Get(ctx, "cockroachsql:clientcert")
}

// Maximum wait for connection, in seconds. Zero or not specified means wait indefinitely.
func GetConnectTimeout(ctx *pulumi.Context) int {
	v, err := config.TryInt(ctx, "cockroachsql:connectTimeout")
	if err == nil {
		return v
	}
	var value int
	if d := internal.GetEnvOrDefault(180, internal.ParseEnvInt, "PGCONNECT_TIMEOUT"); d != nil {
		value = d.(int)
	}
	return value
}

// The name of the database to connect to (defaults to `defaultdb`).
func GetDatabase(ctx *pulumi.Context) string {
	return config.Get(ctx, "cockroachsql:database")
}

// Database username associated to the connected user (for user name maps)
func GetDatabaseUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "cockroachsql:databaseUsername")
}

// Specify the expected version of CockroachDB.
func GetExpectedVersion(ctx *pulumi.Context) string {
	return config.Get(ctx, "cockroachsql:expectedVersion")
}

// Name of CockroachDB server address to connect to
func GetHost(ctx *pulumi.Context) string {
	return config.Get(ctx, "cockroachsql:host")
}

// Maximum number of connections to establish to the database. Zero means unlimited.
func GetMaxConnections(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "cockroachsql:maxConnections")
}

// Password to be used if the CockroachDB server demands password authentication
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "cockroachsql:password")
}

// The CockroachDB port number to connect to at the server host
func GetPort(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "cockroachsql:port")
}

// Deprecated: Rename CockroachDB provider `sslMode` attribute to `sslmode`
func GetSslMode(ctx *pulumi.Context) string {
	return config.Get(ctx, "cockroachsql:sslMode")
}

// This option determines whether or with what priority a secure SSL TCP/IP connection will be negotiated with the CockroachDB server
func GetSslmode(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "cockroachsql:sslmode")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "PGSSLMODE"); d != nil {
		value = d.(string)
	}
	return value
}

// The SSL server root certificate file path. The file must contain PEM encoded data.
func GetSslrootcert(ctx *pulumi.Context) string {
	return config.Get(ctx, "cockroachsql:sslrootcert")
}

// Specify if the user to connect as is a CockroachDB superuser or not.
func GetSuperuser(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "cockroachsql:superuser")
}

// Connection URL for CockroachDB. If set, this overrides other connection parameters.
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "cockroachsql:url")
}

// CockroachDB user name to connect as
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "cockroachsql:username")
}
