// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CockroachSql.Outputs
{

    [OutputType]
    public sealed class GetSequencesSequenceResult
    {
        public readonly string DataType;
        public readonly string ObjectName;
        public readonly string SchemaName;

        [OutputConstructor]
        private GetSequencesSequenceResult(
            string dataType,

            string objectName,

            string schemaName)
        {
            DataType = dataType;
            ObjectName = objectName;
            SchemaName = schemaName;
        }
    }
}
