// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CockroachSql.Outputs
{

    [OutputType]
    public sealed class GetTablesTableResult
    {
        public readonly string ObjectName;
        public readonly string SchemaName;
        public readonly string TableType;

        [OutputConstructor]
        private GetTablesTableResult(
            string objectName,

            string schemaName,

            string tableType)
        {
            ObjectName = objectName;
            SchemaName = schemaName;
            TableType = tableType;
        }
    }
}
