# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .database import *
from .default_privileges import *
from .get_schemas import *
from .get_sequences import *
from .get_tables import *
from .grant import *
from .grant_role import *
from .provider import *
from .role import *
from .schema import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_cockroachsql.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_cockroachsql.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "cockroachsql",
  "mod": "index/database",
  "fqn": "pulumi_cockroachsql",
  "classes": {
   "cockroachsql:index/database:Database": "Database"
  }
 },
 {
  "pkg": "cockroachsql",
  "mod": "index/defaultPrivileges",
  "fqn": "pulumi_cockroachsql",
  "classes": {
   "cockroachsql:index/defaultPrivileges:DefaultPrivileges": "DefaultPrivileges"
  }
 },
 {
  "pkg": "cockroachsql",
  "mod": "index/grant",
  "fqn": "pulumi_cockroachsql",
  "classes": {
   "cockroachsql:index/grant:Grant": "Grant"
  }
 },
 {
  "pkg": "cockroachsql",
  "mod": "index/grantRole",
  "fqn": "pulumi_cockroachsql",
  "classes": {
   "cockroachsql:index/grantRole:GrantRole": "GrantRole"
  }
 },
 {
  "pkg": "cockroachsql",
  "mod": "index/role",
  "fqn": "pulumi_cockroachsql",
  "classes": {
   "cockroachsql:index/role:Role": "Role"
  }
 },
 {
  "pkg": "cockroachsql",
  "mod": "index/schema",
  "fqn": "pulumi_cockroachsql",
  "classes": {
   "cockroachsql:index/schema:Schema": "Schema"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "cockroachsql",
  "token": "pulumi:providers:cockroachsql",
  "fqn": "pulumi_cockroachsql",
  "class": "Provider"
 }
]
"""
)
