# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'ProviderClientcertArgs',
    'ProviderClientcertArgsDict',
]

class ProviderClientcertArgsDict(TypedDict):
    cert: pulumi.Input[_builtins.str]
    """
    The SSL client certificate file path. The file must contain PEM encoded data.
    """
    key: pulumi.Input[_builtins.str]
    """
    The SSL client certificate private key file path. The file must contain PEM encoded data.
    """
    sslinline: NotRequired[pulumi.Input[Optional[_builtins.bool]]]
    """
    Must be set to true if you are inlining the cert/key instead of using a file path.
    """

@pulumi.input_type
class ProviderClientcertArgs:
    def __init__(__self__, *,
                 cert: pulumi.Input[_builtins.str],
                 key: pulumi.Input[_builtins.str],
                 sslinline: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        :param pulumi.Input[_builtins.str] cert: The SSL client certificate file path. The file must contain PEM encoded data.
        :param pulumi.Input[_builtins.str] key: The SSL client certificate private key file path. The file must contain PEM encoded data.
        :param pulumi.Input[_builtins.bool] sslinline: Must be set to true if you are inlining the cert/key instead of using a file path.
        """
        pulumi.set(__self__, "cert", cert)
        pulumi.set(__self__, "key", key)
        if sslinline is not None:
            pulumi.set(__self__, "sslinline", sslinline)

    @_builtins.property
    @pulumi.getter
    def cert(self) -> pulumi.Input[_builtins.str]:
        """
        The SSL client certificate file path. The file must contain PEM encoded data.
        """
        return pulumi.get(self, "cert")

    @cert.setter
    def cert(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cert", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Input[_builtins.str]:
        """
        The SSL client certificate private key file path. The file must contain PEM encoded data.
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def sslinline(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Must be set to true if you are inlining the cert/key instead of using a file path.
        """
        return pulumi.get(self, "sslinline")

    @sslinline.setter
    def sslinline(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "sslinline", value)


