# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['GrantArgs', 'Grant']

@pulumi.input_type
class GrantArgs:
    def __init__(__self__, *,
                 database: pulumi.Input[_builtins.str],
                 object_type: pulumi.Input[_builtins.str],
                 privileges: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 role: pulumi.Input[_builtins.str],
                 columns: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 objects: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 schema: pulumi.Input[Optional[_builtins.str]] = None,
                 with_grant_option: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a Grant resource.

        :param pulumi.Input[_builtins.str] database: The database to grant privileges on for this role
        :param pulumi.Input[_builtins.str] object_type: The CockroachSQL object type to grant the privileges on (one of: database, function, procedure, routine, schema, sequence, table, foreign_data_wrapper, foreign_server, column)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] privileges: The list of privileges to grant
        :param pulumi.Input[_builtins.str] role: The name of the role to grant privileges on
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] columns: The specific columns to grant privileges on for this role
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] objects: The specific objects to grant privileges on for this role (empty means all objects of the requested type)
        :param pulumi.Input[_builtins.str] schema: The database schema to grant privileges on for this role
        :param pulumi.Input[_builtins.bool] with_grant_option: Permit the grant recipient to grant it to others
        """
        pulumi.set(__self__, "database", database)
        pulumi.set(__self__, "object_type", object_type)
        pulumi.set(__self__, "privileges", privileges)
        pulumi.set(__self__, "role", role)
        if columns is not None:
            pulumi.set(__self__, "columns", columns)
        if objects is not None:
            pulumi.set(__self__, "objects", objects)
        if schema is not None:
            pulumi.set(__self__, "schema", schema)
        if with_grant_option is not None:
            pulumi.set(__self__, "with_grant_option", with_grant_option)

    @_builtins.property
    @pulumi.getter
    def database(self) -> pulumi.Input[_builtins.str]:
        """
        The database to grant privileges on for this role
        """
        return pulumi.get(self, "database")

    @database.setter
    def database(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "database", value)

    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> pulumi.Input[_builtins.str]:
        """
        The CockroachSQL object type to grant the privileges on (one of: database, function, procedure, routine, schema, sequence, table, foreign_data_wrapper, foreign_server, column)
        """
        return pulumi.get(self, "object_type")

    @object_type.setter
    def object_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "object_type", value)

    @_builtins.property
    @pulumi.getter
    def privileges(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        The list of privileges to grant
        """
        return pulumi.get(self, "privileges")

    @privileges.setter
    def privileges(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "privileges", value)

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Input[_builtins.str]:
        """
        The name of the role to grant privileges on
        """
        return pulumi.get(self, "role")

    @role.setter
    def role(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "role", value)

    @_builtins.property
    @pulumi.getter
    def columns(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The specific columns to grant privileges on for this role
        """
        return pulumi.get(self, "columns")

    @columns.setter
    def columns(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "columns", value)

    @_builtins.property
    @pulumi.getter
    def objects(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The specific objects to grant privileges on for this role (empty means all objects of the requested type)
        """
        return pulumi.get(self, "objects")

    @objects.setter
    def objects(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "objects", value)

    @_builtins.property
    @pulumi.getter
    def schema(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The database schema to grant privileges on for this role
        """
        return pulumi.get(self, "schema")

    @schema.setter
    def schema(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "schema", value)

    @_builtins.property
    @pulumi.getter(name="withGrantOption")
    def with_grant_option(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Permit the grant recipient to grant it to others
        """
        return pulumi.get(self, "with_grant_option")

    @with_grant_option.setter
    def with_grant_option(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "with_grant_option", value)


@pulumi.input_type
class _GrantState:
    def __init__(__self__, *,
                 columns: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 database: pulumi.Input[Optional[_builtins.str]] = None,
                 object_type: pulumi.Input[Optional[_builtins.str]] = None,
                 objects: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 privileges: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 schema: pulumi.Input[Optional[_builtins.str]] = None,
                 with_grant_option: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        Input properties used for looking up and filtering Grant resources.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] columns: The specific columns to grant privileges on for this role
        :param pulumi.Input[_builtins.str] database: The database to grant privileges on for this role
        :param pulumi.Input[_builtins.str] object_type: The CockroachSQL object type to grant the privileges on (one of: database, function, procedure, routine, schema, sequence, table, foreign_data_wrapper, foreign_server, column)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] objects: The specific objects to grant privileges on for this role (empty means all objects of the requested type)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] privileges: The list of privileges to grant
        :param pulumi.Input[_builtins.str] role: The name of the role to grant privileges on
        :param pulumi.Input[_builtins.str] schema: The database schema to grant privileges on for this role
        :param pulumi.Input[_builtins.bool] with_grant_option: Permit the grant recipient to grant it to others
        """
        if columns is not None:
            pulumi.set(__self__, "columns", columns)
        if database is not None:
            pulumi.set(__self__, "database", database)
        if object_type is not None:
            pulumi.set(__self__, "object_type", object_type)
        if objects is not None:
            pulumi.set(__self__, "objects", objects)
        if privileges is not None:
            pulumi.set(__self__, "privileges", privileges)
        if role is not None:
            pulumi.set(__self__, "role", role)
        if schema is not None:
            pulumi.set(__self__, "schema", schema)
        if with_grant_option is not None:
            pulumi.set(__self__, "with_grant_option", with_grant_option)

    @_builtins.property
    @pulumi.getter
    def columns(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The specific columns to grant privileges on for this role
        """
        return pulumi.get(self, "columns")

    @columns.setter
    def columns(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "columns", value)

    @_builtins.property
    @pulumi.getter
    def database(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The database to grant privileges on for this role
        """
        return pulumi.get(self, "database")

    @database.setter
    def database(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "database", value)

    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The CockroachSQL object type to grant the privileges on (one of: database, function, procedure, routine, schema, sequence, table, foreign_data_wrapper, foreign_server, column)
        """
        return pulumi.get(self, "object_type")

    @object_type.setter
    def object_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "object_type", value)

    @_builtins.property
    @pulumi.getter
    def objects(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The specific objects to grant privileges on for this role (empty means all objects of the requested type)
        """
        return pulumi.get(self, "objects")

    @objects.setter
    def objects(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "objects", value)

    @_builtins.property
    @pulumi.getter
    def privileges(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The list of privileges to grant
        """
        return pulumi.get(self, "privileges")

    @privileges.setter
    def privileges(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "privileges", value)

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the role to grant privileges on
        """
        return pulumi.get(self, "role")

    @role.setter
    def role(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "role", value)

    @_builtins.property
    @pulumi.getter
    def schema(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The database schema to grant privileges on for this role
        """
        return pulumi.get(self, "schema")

    @schema.setter
    def schema(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "schema", value)

    @_builtins.property
    @pulumi.getter(name="withGrantOption")
    def with_grant_option(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Permit the grant recipient to grant it to others
        """
        return pulumi.get(self, "with_grant_option")

    @with_grant_option.setter
    def with_grant_option(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "with_grant_option", value)


@pulumi.type_token("cockroachsql:index/grant:Grant")
class Grant(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 columns: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 database: pulumi.Input[Optional[_builtins.str]] = None,
                 object_type: pulumi.Input[Optional[_builtins.str]] = None,
                 objects: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 privileges: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 schema: pulumi.Input[Optional[_builtins.str]] = None,
                 with_grant_option: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        Create a Grant resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] columns: The specific columns to grant privileges on for this role
        :param pulumi.Input[_builtins.str] database: The database to grant privileges on for this role
        :param pulumi.Input[_builtins.str] object_type: The CockroachSQL object type to grant the privileges on (one of: database, function, procedure, routine, schema, sequence, table, foreign_data_wrapper, foreign_server, column)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] objects: The specific objects to grant privileges on for this role (empty means all objects of the requested type)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] privileges: The list of privileges to grant
        :param pulumi.Input[_builtins.str] role: The name of the role to grant privileges on
        :param pulumi.Input[_builtins.str] schema: The database schema to grant privileges on for this role
        :param pulumi.Input[_builtins.bool] with_grant_option: Permit the grant recipient to grant it to others
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: GrantArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Grant resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param GrantArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(GrantArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 columns: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 database: pulumi.Input[Optional[_builtins.str]] = None,
                 object_type: pulumi.Input[Optional[_builtins.str]] = None,
                 objects: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 privileges: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 schema: pulumi.Input[Optional[_builtins.str]] = None,
                 with_grant_option: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = GrantArgs.__new__(GrantArgs)

            __props__.__dict__["columns"] = columns
            if database is None and not opts.urn:
                raise TypeError("Missing required property 'database'")
            __props__.__dict__["database"] = database
            if object_type is None and not opts.urn:
                raise TypeError("Missing required property 'object_type'")
            __props__.__dict__["object_type"] = object_type
            __props__.__dict__["objects"] = objects
            if privileges is None and not opts.urn:
                raise TypeError("Missing required property 'privileges'")
            __props__.__dict__["privileges"] = privileges
            if role is None and not opts.urn:
                raise TypeError("Missing required property 'role'")
            __props__.__dict__["role"] = role
            __props__.__dict__["schema"] = schema
            __props__.__dict__["with_grant_option"] = with_grant_option
        super(Grant, __self__).__init__(
            'cockroachsql:index/grant:Grant',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            columns: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            database: pulumi.Input[Optional[_builtins.str]] = None,
            object_type: pulumi.Input[Optional[_builtins.str]] = None,
            objects: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            privileges: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            role: pulumi.Input[Optional[_builtins.str]] = None,
            schema: pulumi.Input[Optional[_builtins.str]] = None,
            with_grant_option: pulumi.Input[Optional[_builtins.bool]] = None) -> 'Grant':
        """
        Get an existing Grant resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] columns: The specific columns to grant privileges on for this role
        :param pulumi.Input[_builtins.str] database: The database to grant privileges on for this role
        :param pulumi.Input[_builtins.str] object_type: The CockroachSQL object type to grant the privileges on (one of: database, function, procedure, routine, schema, sequence, table, foreign_data_wrapper, foreign_server, column)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] objects: The specific objects to grant privileges on for this role (empty means all objects of the requested type)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] privileges: The list of privileges to grant
        :param pulumi.Input[_builtins.str] role: The name of the role to grant privileges on
        :param pulumi.Input[_builtins.str] schema: The database schema to grant privileges on for this role
        :param pulumi.Input[_builtins.bool] with_grant_option: Permit the grant recipient to grant it to others
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _GrantState.__new__(_GrantState)

        __props__.__dict__["columns"] = columns
        __props__.__dict__["database"] = database
        __props__.__dict__["object_type"] = object_type
        __props__.__dict__["objects"] = objects
        __props__.__dict__["privileges"] = privileges
        __props__.__dict__["role"] = role
        __props__.__dict__["schema"] = schema
        __props__.__dict__["with_grant_option"] = with_grant_option
        return Grant(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def columns(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        The specific columns to grant privileges on for this role
        """
        return pulumi.get(self, "columns")

    @_builtins.property
    @pulumi.getter
    def database(self) -> pulumi.Output[_builtins.str]:
        """
        The database to grant privileges on for this role
        """
        return pulumi.get(self, "database")

    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> pulumi.Output[_builtins.str]:
        """
        The CockroachSQL object type to grant the privileges on (one of: database, function, procedure, routine, schema, sequence, table, foreign_data_wrapper, foreign_server, column)
        """
        return pulumi.get(self, "object_type")

    @_builtins.property
    @pulumi.getter
    def objects(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        The specific objects to grant privileges on for this role (empty means all objects of the requested type)
        """
        return pulumi.get(self, "objects")

    @_builtins.property
    @pulumi.getter
    def privileges(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        The list of privileges to grant
        """
        return pulumi.get(self, "privileges")

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the role to grant privileges on
        """
        return pulumi.get(self, "role")

    @_builtins.property
    @pulumi.getter
    def schema(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The database schema to grant privileges on for this role
        """
        return pulumi.get(self, "schema")

    @_builtins.property
    @pulumi.getter(name="withGrantOption")
    def with_grant_option(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Permit the grant recipient to grant it to others
        """
        return pulumi.get(self, "with_grant_option")

