# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetSequencesSequenceResult',
    'GetTablesTableResult',
]

@pulumi.output_type
class GetSequencesSequenceResult(dict):
    def __init__(__self__, *,
                 data_type: _builtins.str,
                 object_name: _builtins.str,
                 schema_name: _builtins.str):
        pulumi.set(__self__, "data_type", data_type)
        pulumi.set(__self__, "object_name", object_name)
        pulumi.set(__self__, "schema_name", schema_name)

    @_builtins.property
    @pulumi.getter(name="dataType")
    def data_type(self) -> _builtins.str:
        return pulumi.get(self, "data_type")

    @_builtins.property
    @pulumi.getter(name="objectName")
    def object_name(self) -> _builtins.str:
        return pulumi.get(self, "object_name")

    @_builtins.property
    @pulumi.getter(name="schemaName")
    def schema_name(self) -> _builtins.str:
        return pulumi.get(self, "schema_name")


@pulumi.output_type
class GetTablesTableResult(dict):
    def __init__(__self__, *,
                 object_name: _builtins.str,
                 schema_name: _builtins.str,
                 table_type: _builtins.str):
        pulumi.set(__self__, "object_name", object_name)
        pulumi.set(__self__, "schema_name", schema_name)
        pulumi.set(__self__, "table_type", table_type)

    @_builtins.property
    @pulumi.getter(name="objectName")
    def object_name(self) -> _builtins.str:
        return pulumi.get(self, "object_name")

    @_builtins.property
    @pulumi.getter(name="schemaName")
    def schema_name(self) -> _builtins.str:
        return pulumi.get(self, "schema_name")

    @_builtins.property
    @pulumi.getter(name="tableType")
    def table_type(self) -> _builtins.str:
        return pulumi.get(self, "table_type")


