# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._inputs import *

__all__ = ['ProviderArgs', 'Provider']

@pulumi.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 clientcert: pulumi.Input[Optional['ProviderClientcertArgs']] = None,
                 connect_timeout: pulumi.Input[Optional[_builtins.int]] = None,
                 database: pulumi.Input[Optional[_builtins.str]] = None,
                 database_username: pulumi.Input[Optional[_builtins.str]] = None,
                 expected_version: pulumi.Input[Optional[_builtins.str]] = None,
                 host: pulumi.Input[Optional[_builtins.str]] = None,
                 max_connections: pulumi.Input[Optional[_builtins.int]] = None,
                 password: pulumi.Input[Optional[_builtins.str]] = None,
                 port: pulumi.Input[Optional[_builtins.int]] = None,
                 ssl_mode: pulumi.Input[Optional[_builtins.str]] = None,
                 sslmode: pulumi.Input[Optional[_builtins.str]] = None,
                 sslrootcert: pulumi.Input[Optional[_builtins.str]] = None,
                 superuser: pulumi.Input[Optional[_builtins.bool]] = None,
                 url: pulumi.Input[Optional[_builtins.str]] = None,
                 username: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Provider resource.

        :param pulumi.Input['ProviderClientcertArgs'] clientcert: SSL client certificate if required by the database.
        :param pulumi.Input[_builtins.int] connect_timeout: Maximum wait for connection, in seconds. Zero or not specified means wait indefinitely.
        :param pulumi.Input[_builtins.str] database: The name of the database to connect to (defaults to `defaultdb`).
        :param pulumi.Input[_builtins.str] database_username: Database username associated to the connected user (for user name maps)
        :param pulumi.Input[_builtins.str] expected_version: Specify the expected version of CockroachDB.
        :param pulumi.Input[_builtins.str] host: Name of CockroachDB server address to connect to
        :param pulumi.Input[_builtins.int] max_connections: Maximum number of connections to establish to the database. Zero means unlimited.
        :param pulumi.Input[_builtins.str] password: Password to be used if the CockroachDB server demands password authentication
        :param pulumi.Input[_builtins.int] port: The CockroachDB port number to connect to at the server host
        :param pulumi.Input[_builtins.str] sslmode: This option determines whether or with what priority a secure SSL TCP/IP connection will be negotiated with the CockroachDB server
        :param pulumi.Input[_builtins.str] sslrootcert: The SSL server root certificate file path. The file must contain PEM encoded data.
        :param pulumi.Input[_builtins.bool] superuser: Specify if the user to connect as is a CockroachDB superuser or not.
        :param pulumi.Input[_builtins.str] url: Connection URL for CockroachDB. If set, this overrides other connection parameters.
        :param pulumi.Input[_builtins.str] username: CockroachDB user name to connect as
        """
        if clientcert is not None:
            pulumi.set(__self__, "clientcert", clientcert)
        if connect_timeout is None:
            connect_timeout = (_utilities.get_env_int('PGCONNECT_TIMEOUT') or 180)
        if connect_timeout is not None:
            pulumi.set(__self__, "connect_timeout", connect_timeout)
        if database is not None:
            pulumi.set(__self__, "database", database)
        if database_username is not None:
            pulumi.set(__self__, "database_username", database_username)
        if expected_version is not None:
            pulumi.set(__self__, "expected_version", expected_version)
        if host is not None:
            pulumi.set(__self__, "host", host)
        if max_connections is not None:
            pulumi.set(__self__, "max_connections", max_connections)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if port is not None:
            pulumi.set(__self__, "port", port)
        if ssl_mode is not None:
            warnings.warn("""Rename CockroachDB provider `ssl_mode` attribute to `sslmode`""", DeprecationWarning)
            pulumi.log.warn("""ssl_mode is deprecated: Rename CockroachDB provider `ssl_mode` attribute to `sslmode`""")
        if ssl_mode is not None:
            pulumi.set(__self__, "ssl_mode", ssl_mode)
        if sslmode is None:
            sslmode = _utilities.get_env('PGSSLMODE')
        if sslmode is not None:
            pulumi.set(__self__, "sslmode", sslmode)
        if sslrootcert is not None:
            pulumi.set(__self__, "sslrootcert", sslrootcert)
        if superuser is not None:
            pulumi.set(__self__, "superuser", superuser)
        if url is not None:
            pulumi.set(__self__, "url", url)
        if username is not None:
            pulumi.set(__self__, "username", username)

    @_builtins.property
    @pulumi.getter
    def clientcert(self) -> pulumi.Input[Optional['ProviderClientcertArgs']]:
        """
        SSL client certificate if required by the database.
        """
        return pulumi.get(self, "clientcert")

    @clientcert.setter
    def clientcert(self, value: pulumi.Input[Optional['ProviderClientcertArgs']]):
        pulumi.set(self, "clientcert", value)

    @_builtins.property
    @pulumi.getter(name="connectTimeout")
    def connect_timeout(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Maximum wait for connection, in seconds. Zero or not specified means wait indefinitely.
        """
        return pulumi.get(self, "connect_timeout")

    @connect_timeout.setter
    def connect_timeout(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "connect_timeout", value)

    @_builtins.property
    @pulumi.getter
    def database(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the database to connect to (defaults to `defaultdb`).
        """
        return pulumi.get(self, "database")

    @database.setter
    def database(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "database", value)

    @_builtins.property
    @pulumi.getter(name="databaseUsername")
    def database_username(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Database username associated to the connected user (for user name maps)
        """
        return pulumi.get(self, "database_username")

    @database_username.setter
    def database_username(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "database_username", value)

    @_builtins.property
    @pulumi.getter(name="expectedVersion")
    def expected_version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Specify the expected version of CockroachDB.
        """
        return pulumi.get(self, "expected_version")

    @expected_version.setter
    def expected_version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "expected_version", value)

    @_builtins.property
    @pulumi.getter
    def host(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of CockroachDB server address to connect to
        """
        return pulumi.get(self, "host")

    @host.setter
    def host(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "host", value)

    @_builtins.property
    @pulumi.getter(name="maxConnections")
    def max_connections(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Maximum number of connections to establish to the database. Zero means unlimited.
        """
        return pulumi.get(self, "max_connections")

    @max_connections.setter
    def max_connections(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "max_connections", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Password to be used if the CockroachDB server demands password authentication
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter
    def port(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The CockroachDB port number to connect to at the server host
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "port", value)

    @_builtins.property
    @pulumi.getter(name="sslMode")
    @_utilities.deprecated("""Rename CockroachDB provider `ssl_mode` attribute to `sslmode`""")
    def ssl_mode(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "ssl_mode")

    @ssl_mode.setter
    def ssl_mode(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ssl_mode", value)

    @_builtins.property
    @pulumi.getter
    def sslmode(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        This option determines whether or with what priority a secure SSL TCP/IP connection will be negotiated with the CockroachDB server
        """
        return pulumi.get(self, "sslmode")

    @sslmode.setter
    def sslmode(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "sslmode", value)

    @_builtins.property
    @pulumi.getter
    def sslrootcert(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The SSL server root certificate file path. The file must contain PEM encoded data.
        """
        return pulumi.get(self, "sslrootcert")

    @sslrootcert.setter
    def sslrootcert(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "sslrootcert", value)

    @_builtins.property
    @pulumi.getter
    def superuser(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Specify if the user to connect as is a CockroachDB superuser or not.
        """
        return pulumi.get(self, "superuser")

    @superuser.setter
    def superuser(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "superuser", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Connection URL for CockroachDB. If set, this overrides other connection parameters.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        CockroachDB user name to connect as
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "username", value)


@pulumi.type_token("pulumi:providers:cockroachsql")
class Provider(pulumi.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 clientcert: pulumi.Input[Optional[Union['ProviderClientcertArgs', 'ProviderClientcertArgsDict']]] = None,
                 connect_timeout: pulumi.Input[Optional[_builtins.int]] = None,
                 database: pulumi.Input[Optional[_builtins.str]] = None,
                 database_username: pulumi.Input[Optional[_builtins.str]] = None,
                 expected_version: pulumi.Input[Optional[_builtins.str]] = None,
                 host: pulumi.Input[Optional[_builtins.str]] = None,
                 max_connections: pulumi.Input[Optional[_builtins.int]] = None,
                 password: pulumi.Input[Optional[_builtins.str]] = None,
                 port: pulumi.Input[Optional[_builtins.int]] = None,
                 ssl_mode: pulumi.Input[Optional[_builtins.str]] = None,
                 sslmode: pulumi.Input[Optional[_builtins.str]] = None,
                 sslrootcert: pulumi.Input[Optional[_builtins.str]] = None,
                 superuser: pulumi.Input[Optional[_builtins.bool]] = None,
                 url: pulumi.Input[Optional[_builtins.str]] = None,
                 username: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        The provider type for the cockroachsql package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['ProviderClientcertArgs', 'ProviderClientcertArgsDict']] clientcert: SSL client certificate if required by the database.
        :param pulumi.Input[_builtins.int] connect_timeout: Maximum wait for connection, in seconds. Zero or not specified means wait indefinitely.
        :param pulumi.Input[_builtins.str] database: The name of the database to connect to (defaults to `defaultdb`).
        :param pulumi.Input[_builtins.str] database_username: Database username associated to the connected user (for user name maps)
        :param pulumi.Input[_builtins.str] expected_version: Specify the expected version of CockroachDB.
        :param pulumi.Input[_builtins.str] host: Name of CockroachDB server address to connect to
        :param pulumi.Input[_builtins.int] max_connections: Maximum number of connections to establish to the database. Zero means unlimited.
        :param pulumi.Input[_builtins.str] password: Password to be used if the CockroachDB server demands password authentication
        :param pulumi.Input[_builtins.int] port: The CockroachDB port number to connect to at the server host
        :param pulumi.Input[_builtins.str] sslmode: This option determines whether or with what priority a secure SSL TCP/IP connection will be negotiated with the CockroachDB server
        :param pulumi.Input[_builtins.str] sslrootcert: The SSL server root certificate file path. The file must contain PEM encoded data.
        :param pulumi.Input[_builtins.bool] superuser: Specify if the user to connect as is a CockroachDB superuser or not.
        :param pulumi.Input[_builtins.str] url: Connection URL for CockroachDB. If set, this overrides other connection parameters.
        :param pulumi.Input[_builtins.str] username: CockroachDB user name to connect as
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProviderArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The provider type for the cockroachsql package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.


        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 clientcert: pulumi.Input[Optional[Union['ProviderClientcertArgs', 'ProviderClientcertArgsDict']]] = None,
                 connect_timeout: pulumi.Input[Optional[_builtins.int]] = None,
                 database: pulumi.Input[Optional[_builtins.str]] = None,
                 database_username: pulumi.Input[Optional[_builtins.str]] = None,
                 expected_version: pulumi.Input[Optional[_builtins.str]] = None,
                 host: pulumi.Input[Optional[_builtins.str]] = None,
                 max_connections: pulumi.Input[Optional[_builtins.int]] = None,
                 password: pulumi.Input[Optional[_builtins.str]] = None,
                 port: pulumi.Input[Optional[_builtins.int]] = None,
                 ssl_mode: pulumi.Input[Optional[_builtins.str]] = None,
                 sslmode: pulumi.Input[Optional[_builtins.str]] = None,
                 sslrootcert: pulumi.Input[Optional[_builtins.str]] = None,
                 superuser: pulumi.Input[Optional[_builtins.bool]] = None,
                 url: pulumi.Input[Optional[_builtins.str]] = None,
                 username: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            __props__.__dict__["clientcert"] = pulumi.Output.from_input(clientcert).apply(pulumi.runtime.to_json) if clientcert is not None else None
            if connect_timeout is None:
                connect_timeout = (_utilities.get_env_int('PGCONNECT_TIMEOUT') or 180)
            __props__.__dict__["connect_timeout"] = pulumi.Output.from_input(connect_timeout).apply(pulumi.runtime.to_json) if connect_timeout is not None else None
            __props__.__dict__["database"] = database
            __props__.__dict__["database_username"] = database_username
            __props__.__dict__["expected_version"] = expected_version
            __props__.__dict__["host"] = host
            __props__.__dict__["max_connections"] = pulumi.Output.from_input(max_connections).apply(pulumi.runtime.to_json) if max_connections is not None else None
            __props__.__dict__["password"] = None if password is None else pulumi.Output.secret(password)
            __props__.__dict__["port"] = pulumi.Output.from_input(port).apply(pulumi.runtime.to_json) if port is not None else None
            __props__.__dict__["ssl_mode"] = ssl_mode
            if sslmode is None:
                sslmode = _utilities.get_env('PGSSLMODE')
            __props__.__dict__["sslmode"] = sslmode
            __props__.__dict__["sslrootcert"] = sslrootcert
            __props__.__dict__["superuser"] = pulumi.Output.from_input(superuser).apply(pulumi.runtime.to_json) if superuser is not None else None
            __props__.__dict__["url"] = None if url is None else pulumi.Output.secret(url)
            __props__.__dict__["username"] = username
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["password", "url"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Provider, __self__).__init__(
            'cockroachsql',
            resource_name,
            __props__,
            opts)

    @_builtins.property
    @pulumi.getter
    def database(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The name of the database to connect to (defaults to `defaultdb`).
        """
        return pulumi.get(self, "database")

    @_builtins.property
    @pulumi.getter(name="databaseUsername")
    def database_username(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Database username associated to the connected user (for user name maps)
        """
        return pulumi.get(self, "database_username")

    @_builtins.property
    @pulumi.getter(name="expectedVersion")
    def expected_version(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Specify the expected version of CockroachDB.
        """
        return pulumi.get(self, "expected_version")

    @_builtins.property
    @pulumi.getter
    def host(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Name of CockroachDB server address to connect to
        """
        return pulumi.get(self, "host")

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Password to be used if the CockroachDB server demands password authentication
        """
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter(name="sslMode")
    @_utilities.deprecated("""Rename CockroachDB provider `ssl_mode` attribute to `sslmode`""")
    def ssl_mode(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ssl_mode")

    @_builtins.property
    @pulumi.getter
    def sslmode(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        This option determines whether or with what priority a secure SSL TCP/IP connection will be negotiated with the CockroachDB server
        """
        return pulumi.get(self, "sslmode")

    @_builtins.property
    @pulumi.getter
    def sslrootcert(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The SSL server root certificate file path. The file must contain PEM encoded data.
        """
        return pulumi.get(self, "sslrootcert")

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Connection URL for CockroachDB. If set, this overrides other connection parameters.
        """
        return pulumi.get(self, "url")

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        CockroachDB user name to connect as
        """
        return pulumi.get(self, "username")

    @pulumi.output_type
    class TerraformConfigResult:
        def __init__(__self__, result=None):
            if result and not isinstance(result, dict):
                raise TypeError("Expected argument 'result' to be a dict")
            pulumi.set(__self__, "result", result)

        @_builtins.property
        @pulumi.getter
        def result(self) -> Mapping[str, Any]:
            return pulumi.get(self, "result")

    def terraform_config(__self__) -> pulumi.Output['Provider.TerraformConfigResult']:
        """
        This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
        """
        __args__ = dict()
        __args__['__self__'] = __self__
        return pulumi.runtime.call('pulumi:providers:cockroachsql/terraformConfig', __args__, res=__self__, typ=Provider.TerraformConfigResult)

