# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['RoleArgs', 'Role']

@pulumi.input_type
class RoleArgs:
    def __init__(__self__, *,
                 create_role: pulumi.Input[Optional[_builtins.bool]] = None,
                 encrypted: pulumi.Input[Optional[_builtins.str]] = None,
                 idle_in_transaction_session_timeout: pulumi.Input[Optional[_builtins.int]] = None,
                 login: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 password: pulumi.Input[Optional[_builtins.str]] = None,
                 password_wo: pulumi.Input[Optional[_builtins.str]] = None,
                 password_wo_version: pulumi.Input[Optional[_builtins.str]] = None,
                 roles: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 search_paths: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 skip_drop_role: pulumi.Input[Optional[_builtins.bool]] = None,
                 skip_reassign_owned: pulumi.Input[Optional[_builtins.bool]] = None,
                 statement_timeout: pulumi.Input[Optional[_builtins.int]] = None,
                 valid_until: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Role resource.

        :param pulumi.Input[_builtins.bool] create_role: Determine whether this role will be permitted to create new roles
        :param pulumi.Input[_builtins.int] idle_in_transaction_session_timeout: Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
        :param pulumi.Input[_builtins.bool] login: Determine whether a role is allowed to log in
        :param pulumi.Input[_builtins.str] name: The name of the role
        :param pulumi.Input[_builtins.str] password: Sets the role's password
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Sets the role's password without storing it in the state file.
        :param pulumi.Input[_builtins.str] password_wo_version: Prevents applies from updating the role password on every apply unless the value changes.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] roles: Role(s) to grant to this new role
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] search_paths: Sets the role's search path
        :param pulumi.Input[_builtins.bool] skip_drop_role: Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
        :param pulumi.Input[_builtins.bool] skip_reassign_owned: Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
        :param pulumi.Input[_builtins.int] statement_timeout: Abort any statement that takes more than the specified number of milliseconds
        :param pulumi.Input[_builtins.str] valid_until: Sets a date and time after which the role's password is no longer valid
        """
        if create_role is not None:
            pulumi.set(__self__, "create_role", create_role)
        if encrypted is not None:
            warnings.warn("""Rename CockroachSQL role resource attribute \"encrypted\"""", DeprecationWarning)
            pulumi.log.warn("""encrypted is deprecated: Rename CockroachSQL role resource attribute \"encrypted\"""")
        if encrypted is not None:
            pulumi.set(__self__, "encrypted", encrypted)
        if idle_in_transaction_session_timeout is not None:
            pulumi.set(__self__, "idle_in_transaction_session_timeout", idle_in_transaction_session_timeout)
        if login is not None:
            pulumi.set(__self__, "login", login)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if password_wo is not None:
            pulumi.set(__self__, "password_wo", password_wo)
        if password_wo_version is not None:
            pulumi.set(__self__, "password_wo_version", password_wo_version)
        if roles is not None:
            pulumi.set(__self__, "roles", roles)
        if search_paths is not None:
            pulumi.set(__self__, "search_paths", search_paths)
        if skip_drop_role is not None:
            pulumi.set(__self__, "skip_drop_role", skip_drop_role)
        if skip_reassign_owned is not None:
            pulumi.set(__self__, "skip_reassign_owned", skip_reassign_owned)
        if statement_timeout is not None:
            pulumi.set(__self__, "statement_timeout", statement_timeout)
        if valid_until is not None:
            pulumi.set(__self__, "valid_until", valid_until)

    @_builtins.property
    @pulumi.getter(name="createRole")
    def create_role(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Determine whether this role will be permitted to create new roles
        """
        return pulumi.get(self, "create_role")

    @create_role.setter
    def create_role(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "create_role", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Rename CockroachSQL role resource attribute \"encrypted\"""")
    def encrypted(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "encrypted")

    @encrypted.setter
    def encrypted(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "encrypted", value)

    @_builtins.property
    @pulumi.getter(name="idleInTransactionSessionTimeout")
    def idle_in_transaction_session_timeout(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
        """
        return pulumi.get(self, "idle_in_transaction_session_timeout")

    @idle_in_transaction_session_timeout.setter
    def idle_in_transaction_session_timeout(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "idle_in_transaction_session_timeout", value)

    @_builtins.property
    @pulumi.getter
    def login(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Determine whether a role is allowed to log in
        """
        return pulumi.get(self, "login")

    @login.setter
    def login(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "login", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the role
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Sets the role's password
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter(name="passwordWo")
    def password_wo(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        Sets the role's password without storing it in the state file.
        """
        return pulumi.get(self, "password_wo")

    @password_wo.setter
    def password_wo(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "password_wo", value)

    @_builtins.property
    @pulumi.getter(name="passwordWoVersion")
    def password_wo_version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Prevents applies from updating the role password on every apply unless the value changes.
        """
        return pulumi.get(self, "password_wo_version")

    @password_wo_version.setter
    def password_wo_version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "password_wo_version", value)

    @_builtins.property
    @pulumi.getter
    def roles(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Role(s) to grant to this new role
        """
        return pulumi.get(self, "roles")

    @roles.setter
    def roles(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "roles", value)

    @_builtins.property
    @pulumi.getter(name="searchPaths")
    def search_paths(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Sets the role's search path
        """
        return pulumi.get(self, "search_paths")

    @search_paths.setter
    def search_paths(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "search_paths", value)

    @_builtins.property
    @pulumi.getter(name="skipDropRole")
    def skip_drop_role(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
        """
        return pulumi.get(self, "skip_drop_role")

    @skip_drop_role.setter
    def skip_drop_role(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "skip_drop_role", value)

    @_builtins.property
    @pulumi.getter(name="skipReassignOwned")
    def skip_reassign_owned(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
        """
        return pulumi.get(self, "skip_reassign_owned")

    @skip_reassign_owned.setter
    def skip_reassign_owned(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "skip_reassign_owned", value)

    @_builtins.property
    @pulumi.getter(name="statementTimeout")
    def statement_timeout(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Abort any statement that takes more than the specified number of milliseconds
        """
        return pulumi.get(self, "statement_timeout")

    @statement_timeout.setter
    def statement_timeout(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "statement_timeout", value)

    @_builtins.property
    @pulumi.getter(name="validUntil")
    def valid_until(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Sets a date and time after which the role's password is no longer valid
        """
        return pulumi.get(self, "valid_until")

    @valid_until.setter
    def valid_until(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "valid_until", value)


@pulumi.input_type
class _RoleState:
    def __init__(__self__, *,
                 create_role: pulumi.Input[Optional[_builtins.bool]] = None,
                 encrypted: pulumi.Input[Optional[_builtins.str]] = None,
                 idle_in_transaction_session_timeout: pulumi.Input[Optional[_builtins.int]] = None,
                 login: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 password: pulumi.Input[Optional[_builtins.str]] = None,
                 password_wo: pulumi.Input[Optional[_builtins.str]] = None,
                 password_wo_version: pulumi.Input[Optional[_builtins.str]] = None,
                 roles: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 search_paths: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 skip_drop_role: pulumi.Input[Optional[_builtins.bool]] = None,
                 skip_reassign_owned: pulumi.Input[Optional[_builtins.bool]] = None,
                 statement_timeout: pulumi.Input[Optional[_builtins.int]] = None,
                 valid_until: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Role resources.

        :param pulumi.Input[_builtins.bool] create_role: Determine whether this role will be permitted to create new roles
        :param pulumi.Input[_builtins.int] idle_in_transaction_session_timeout: Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
        :param pulumi.Input[_builtins.bool] login: Determine whether a role is allowed to log in
        :param pulumi.Input[_builtins.str] name: The name of the role
        :param pulumi.Input[_builtins.str] password: Sets the role's password
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Sets the role's password without storing it in the state file.
        :param pulumi.Input[_builtins.str] password_wo_version: Prevents applies from updating the role password on every apply unless the value changes.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] roles: Role(s) to grant to this new role
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] search_paths: Sets the role's search path
        :param pulumi.Input[_builtins.bool] skip_drop_role: Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
        :param pulumi.Input[_builtins.bool] skip_reassign_owned: Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
        :param pulumi.Input[_builtins.int] statement_timeout: Abort any statement that takes more than the specified number of milliseconds
        :param pulumi.Input[_builtins.str] valid_until: Sets a date and time after which the role's password is no longer valid
        """
        if create_role is not None:
            pulumi.set(__self__, "create_role", create_role)
        if encrypted is not None:
            warnings.warn("""Rename CockroachSQL role resource attribute \"encrypted\"""", DeprecationWarning)
            pulumi.log.warn("""encrypted is deprecated: Rename CockroachSQL role resource attribute \"encrypted\"""")
        if encrypted is not None:
            pulumi.set(__self__, "encrypted", encrypted)
        if idle_in_transaction_session_timeout is not None:
            pulumi.set(__self__, "idle_in_transaction_session_timeout", idle_in_transaction_session_timeout)
        if login is not None:
            pulumi.set(__self__, "login", login)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if password_wo is not None:
            pulumi.set(__self__, "password_wo", password_wo)
        if password_wo_version is not None:
            pulumi.set(__self__, "password_wo_version", password_wo_version)
        if roles is not None:
            pulumi.set(__self__, "roles", roles)
        if search_paths is not None:
            pulumi.set(__self__, "search_paths", search_paths)
        if skip_drop_role is not None:
            pulumi.set(__self__, "skip_drop_role", skip_drop_role)
        if skip_reassign_owned is not None:
            pulumi.set(__self__, "skip_reassign_owned", skip_reassign_owned)
        if statement_timeout is not None:
            pulumi.set(__self__, "statement_timeout", statement_timeout)
        if valid_until is not None:
            pulumi.set(__self__, "valid_until", valid_until)

    @_builtins.property
    @pulumi.getter(name="createRole")
    def create_role(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Determine whether this role will be permitted to create new roles
        """
        return pulumi.get(self, "create_role")

    @create_role.setter
    def create_role(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "create_role", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Rename CockroachSQL role resource attribute \"encrypted\"""")
    def encrypted(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "encrypted")

    @encrypted.setter
    def encrypted(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "encrypted", value)

    @_builtins.property
    @pulumi.getter(name="idleInTransactionSessionTimeout")
    def idle_in_transaction_session_timeout(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
        """
        return pulumi.get(self, "idle_in_transaction_session_timeout")

    @idle_in_transaction_session_timeout.setter
    def idle_in_transaction_session_timeout(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "idle_in_transaction_session_timeout", value)

    @_builtins.property
    @pulumi.getter
    def login(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Determine whether a role is allowed to log in
        """
        return pulumi.get(self, "login")

    @login.setter
    def login(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "login", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the role
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Sets the role's password
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter(name="passwordWo")
    def password_wo(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        Sets the role's password without storing it in the state file.
        """
        return pulumi.get(self, "password_wo")

    @password_wo.setter
    def password_wo(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "password_wo", value)

    @_builtins.property
    @pulumi.getter(name="passwordWoVersion")
    def password_wo_version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Prevents applies from updating the role password on every apply unless the value changes.
        """
        return pulumi.get(self, "password_wo_version")

    @password_wo_version.setter
    def password_wo_version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "password_wo_version", value)

    @_builtins.property
    @pulumi.getter
    def roles(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Role(s) to grant to this new role
        """
        return pulumi.get(self, "roles")

    @roles.setter
    def roles(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "roles", value)

    @_builtins.property
    @pulumi.getter(name="searchPaths")
    def search_paths(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Sets the role's search path
        """
        return pulumi.get(self, "search_paths")

    @search_paths.setter
    def search_paths(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "search_paths", value)

    @_builtins.property
    @pulumi.getter(name="skipDropRole")
    def skip_drop_role(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
        """
        return pulumi.get(self, "skip_drop_role")

    @skip_drop_role.setter
    def skip_drop_role(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "skip_drop_role", value)

    @_builtins.property
    @pulumi.getter(name="skipReassignOwned")
    def skip_reassign_owned(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
        """
        return pulumi.get(self, "skip_reassign_owned")

    @skip_reassign_owned.setter
    def skip_reassign_owned(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "skip_reassign_owned", value)

    @_builtins.property
    @pulumi.getter(name="statementTimeout")
    def statement_timeout(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Abort any statement that takes more than the specified number of milliseconds
        """
        return pulumi.get(self, "statement_timeout")

    @statement_timeout.setter
    def statement_timeout(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "statement_timeout", value)

    @_builtins.property
    @pulumi.getter(name="validUntil")
    def valid_until(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Sets a date and time after which the role's password is no longer valid
        """
        return pulumi.get(self, "valid_until")

    @valid_until.setter
    def valid_until(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "valid_until", value)


@pulumi.type_token("cockroachsql:index/role:Role")
class Role(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 create_role: pulumi.Input[Optional[_builtins.bool]] = None,
                 encrypted: pulumi.Input[Optional[_builtins.str]] = None,
                 idle_in_transaction_session_timeout: pulumi.Input[Optional[_builtins.int]] = None,
                 login: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 password: pulumi.Input[Optional[_builtins.str]] = None,
                 password_wo: pulumi.Input[Optional[_builtins.str]] = None,
                 password_wo_version: pulumi.Input[Optional[_builtins.str]] = None,
                 roles: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 search_paths: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 skip_drop_role: pulumi.Input[Optional[_builtins.bool]] = None,
                 skip_reassign_owned: pulumi.Input[Optional[_builtins.bool]] = None,
                 statement_timeout: pulumi.Input[Optional[_builtins.int]] = None,
                 valid_until: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Role resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] create_role: Determine whether this role will be permitted to create new roles
        :param pulumi.Input[_builtins.int] idle_in_transaction_session_timeout: Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
        :param pulumi.Input[_builtins.bool] login: Determine whether a role is allowed to log in
        :param pulumi.Input[_builtins.str] name: The name of the role
        :param pulumi.Input[_builtins.str] password: Sets the role's password
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Sets the role's password without storing it in the state file.
        :param pulumi.Input[_builtins.str] password_wo_version: Prevents applies from updating the role password on every apply unless the value changes.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] roles: Role(s) to grant to this new role
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] search_paths: Sets the role's search path
        :param pulumi.Input[_builtins.bool] skip_drop_role: Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
        :param pulumi.Input[_builtins.bool] skip_reassign_owned: Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
        :param pulumi.Input[_builtins.int] statement_timeout: Abort any statement that takes more than the specified number of milliseconds
        :param pulumi.Input[_builtins.str] valid_until: Sets a date and time after which the role's password is no longer valid
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[RoleArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Role resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param RoleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RoleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 create_role: pulumi.Input[Optional[_builtins.bool]] = None,
                 encrypted: pulumi.Input[Optional[_builtins.str]] = None,
                 idle_in_transaction_session_timeout: pulumi.Input[Optional[_builtins.int]] = None,
                 login: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 password: pulumi.Input[Optional[_builtins.str]] = None,
                 password_wo: pulumi.Input[Optional[_builtins.str]] = None,
                 password_wo_version: pulumi.Input[Optional[_builtins.str]] = None,
                 roles: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 search_paths: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 skip_drop_role: pulumi.Input[Optional[_builtins.bool]] = None,
                 skip_reassign_owned: pulumi.Input[Optional[_builtins.bool]] = None,
                 statement_timeout: pulumi.Input[Optional[_builtins.int]] = None,
                 valid_until: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RoleArgs.__new__(RoleArgs)

            __props__.__dict__["create_role"] = create_role
            __props__.__dict__["encrypted"] = encrypted
            __props__.__dict__["idle_in_transaction_session_timeout"] = idle_in_transaction_session_timeout
            __props__.__dict__["login"] = login
            __props__.__dict__["name"] = name
            __props__.__dict__["password"] = None if password is None else pulumi.Output.secret(password)
            __props__.__dict__["password_wo"] = None if password_wo is None else pulumi.Output.secret(password_wo)
            __props__.__dict__["password_wo_version"] = password_wo_version
            __props__.__dict__["roles"] = roles
            __props__.__dict__["search_paths"] = search_paths
            __props__.__dict__["skip_drop_role"] = skip_drop_role
            __props__.__dict__["skip_reassign_owned"] = skip_reassign_owned
            __props__.__dict__["statement_timeout"] = statement_timeout
            __props__.__dict__["valid_until"] = valid_until
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["password", "passwordWo"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Role, __self__).__init__(
            'cockroachsql:index/role:Role',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            create_role: pulumi.Input[Optional[_builtins.bool]] = None,
            encrypted: pulumi.Input[Optional[_builtins.str]] = None,
            idle_in_transaction_session_timeout: pulumi.Input[Optional[_builtins.int]] = None,
            login: pulumi.Input[Optional[_builtins.bool]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            password: pulumi.Input[Optional[_builtins.str]] = None,
            password_wo: pulumi.Input[Optional[_builtins.str]] = None,
            password_wo_version: pulumi.Input[Optional[_builtins.str]] = None,
            roles: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            search_paths: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            skip_drop_role: pulumi.Input[Optional[_builtins.bool]] = None,
            skip_reassign_owned: pulumi.Input[Optional[_builtins.bool]] = None,
            statement_timeout: pulumi.Input[Optional[_builtins.int]] = None,
            valid_until: pulumi.Input[Optional[_builtins.str]] = None) -> 'Role':
        """
        Get an existing Role resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] create_role: Determine whether this role will be permitted to create new roles
        :param pulumi.Input[_builtins.int] idle_in_transaction_session_timeout: Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
        :param pulumi.Input[_builtins.bool] login: Determine whether a role is allowed to log in
        :param pulumi.Input[_builtins.str] name: The name of the role
        :param pulumi.Input[_builtins.str] password: Sets the role's password
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Sets the role's password without storing it in the state file.
        :param pulumi.Input[_builtins.str] password_wo_version: Prevents applies from updating the role password on every apply unless the value changes.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] roles: Role(s) to grant to this new role
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] search_paths: Sets the role's search path
        :param pulumi.Input[_builtins.bool] skip_drop_role: Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
        :param pulumi.Input[_builtins.bool] skip_reassign_owned: Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
        :param pulumi.Input[_builtins.int] statement_timeout: Abort any statement that takes more than the specified number of milliseconds
        :param pulumi.Input[_builtins.str] valid_until: Sets a date and time after which the role's password is no longer valid
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _RoleState.__new__(_RoleState)

        __props__.__dict__["create_role"] = create_role
        __props__.__dict__["encrypted"] = encrypted
        __props__.__dict__["idle_in_transaction_session_timeout"] = idle_in_transaction_session_timeout
        __props__.__dict__["login"] = login
        __props__.__dict__["name"] = name
        __props__.__dict__["password"] = password
        __props__.__dict__["password_wo"] = password_wo
        __props__.__dict__["password_wo_version"] = password_wo_version
        __props__.__dict__["roles"] = roles
        __props__.__dict__["search_paths"] = search_paths
        __props__.__dict__["skip_drop_role"] = skip_drop_role
        __props__.__dict__["skip_reassign_owned"] = skip_reassign_owned
        __props__.__dict__["statement_timeout"] = statement_timeout
        __props__.__dict__["valid_until"] = valid_until
        return Role(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="createRole")
    def create_role(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Determine whether this role will be permitted to create new roles
        """
        return pulumi.get(self, "create_role")

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Rename CockroachSQL role resource attribute \"encrypted\"""")
    def encrypted(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "encrypted")

    @_builtins.property
    @pulumi.getter(name="idleInTransactionSessionTimeout")
    def idle_in_transaction_session_timeout(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
        """
        return pulumi.get(self, "idle_in_transaction_session_timeout")

    @_builtins.property
    @pulumi.getter
    def login(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Determine whether a role is allowed to log in
        """
        return pulumi.get(self, "login")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the role
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Sets the role's password
        """
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter(name="passwordWo")
    def password_wo(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        Sets the role's password without storing it in the state file.
        """
        return pulumi.get(self, "password_wo")

    @_builtins.property
    @pulumi.getter(name="passwordWoVersion")
    def password_wo_version(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Prevents applies from updating the role password on every apply unless the value changes.
        """
        return pulumi.get(self, "password_wo_version")

    @_builtins.property
    @pulumi.getter
    def roles(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Role(s) to grant to this new role
        """
        return pulumi.get(self, "roles")

    @_builtins.property
    @pulumi.getter(name="searchPaths")
    def search_paths(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Sets the role's search path
        """
        return pulumi.get(self, "search_paths")

    @_builtins.property
    @pulumi.getter(name="skipDropRole")
    def skip_drop_role(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
        """
        return pulumi.get(self, "skip_drop_role")

    @_builtins.property
    @pulumi.getter(name="skipReassignOwned")
    def skip_reassign_owned(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
        """
        return pulumi.get(self, "skip_reassign_owned")

    @_builtins.property
    @pulumi.getter(name="statementTimeout")
    def statement_timeout(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Abort any statement that takes more than the specified number of milliseconds
        """
        return pulumi.get(self, "statement_timeout")

    @_builtins.property
    @pulumi.getter(name="validUntil")
    def valid_until(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Sets a date and time after which the role's password is no longer valid
        """
        return pulumi.get(self, "valid_until")

