# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SchemaArgs', 'Schema']

@pulumi.input_type
class SchemaArgs:
    def __init__(__self__, *,
                 database: pulumi.Input[Optional[_builtins.str]] = None,
                 drop_cascade: pulumi.Input[Optional[_builtins.bool]] = None,
                 if_not_exists: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 owner: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Schema resource.

        :param pulumi.Input[_builtins.str] database: The database name to alter schema
        :param pulumi.Input[_builtins.bool] drop_cascade: When true, will also drop all the objects that are contained in the schema
        :param pulumi.Input[_builtins.bool] if_not_exists: When true, use the existing schema if it exists
        :param pulumi.Input[_builtins.str] name: The name of the schema
        :param pulumi.Input[_builtins.str] owner: The ROLE name who owns the schema
        """
        if database is not None:
            pulumi.set(__self__, "database", database)
        if drop_cascade is not None:
            pulumi.set(__self__, "drop_cascade", drop_cascade)
        if if_not_exists is not None:
            pulumi.set(__self__, "if_not_exists", if_not_exists)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if owner is not None:
            pulumi.set(__self__, "owner", owner)

    @_builtins.property
    @pulumi.getter
    def database(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The database name to alter schema
        """
        return pulumi.get(self, "database")

    @database.setter
    def database(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "database", value)

    @_builtins.property
    @pulumi.getter(name="dropCascade")
    def drop_cascade(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When true, will also drop all the objects that are contained in the schema
        """
        return pulumi.get(self, "drop_cascade")

    @drop_cascade.setter
    def drop_cascade(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "drop_cascade", value)

    @_builtins.property
    @pulumi.getter(name="ifNotExists")
    def if_not_exists(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When true, use the existing schema if it exists
        """
        return pulumi.get(self, "if_not_exists")

    @if_not_exists.setter
    def if_not_exists(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "if_not_exists", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the schema
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def owner(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ROLE name who owns the schema
        """
        return pulumi.get(self, "owner")

    @owner.setter
    def owner(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "owner", value)


@pulumi.input_type
class _SchemaState:
    def __init__(__self__, *,
                 database: pulumi.Input[Optional[_builtins.str]] = None,
                 drop_cascade: pulumi.Input[Optional[_builtins.bool]] = None,
                 if_not_exists: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 owner: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Schema resources.

        :param pulumi.Input[_builtins.str] database: The database name to alter schema
        :param pulumi.Input[_builtins.bool] drop_cascade: When true, will also drop all the objects that are contained in the schema
        :param pulumi.Input[_builtins.bool] if_not_exists: When true, use the existing schema if it exists
        :param pulumi.Input[_builtins.str] name: The name of the schema
        :param pulumi.Input[_builtins.str] owner: The ROLE name who owns the schema
        """
        if database is not None:
            pulumi.set(__self__, "database", database)
        if drop_cascade is not None:
            pulumi.set(__self__, "drop_cascade", drop_cascade)
        if if_not_exists is not None:
            pulumi.set(__self__, "if_not_exists", if_not_exists)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if owner is not None:
            pulumi.set(__self__, "owner", owner)

    @_builtins.property
    @pulumi.getter
    def database(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The database name to alter schema
        """
        return pulumi.get(self, "database")

    @database.setter
    def database(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "database", value)

    @_builtins.property
    @pulumi.getter(name="dropCascade")
    def drop_cascade(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When true, will also drop all the objects that are contained in the schema
        """
        return pulumi.get(self, "drop_cascade")

    @drop_cascade.setter
    def drop_cascade(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "drop_cascade", value)

    @_builtins.property
    @pulumi.getter(name="ifNotExists")
    def if_not_exists(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When true, use the existing schema if it exists
        """
        return pulumi.get(self, "if_not_exists")

    @if_not_exists.setter
    def if_not_exists(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "if_not_exists", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the schema
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def owner(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ROLE name who owns the schema
        """
        return pulumi.get(self, "owner")

    @owner.setter
    def owner(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "owner", value)


@pulumi.type_token("cockroachsql:index/schema:Schema")
class Schema(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 database: pulumi.Input[Optional[_builtins.str]] = None,
                 drop_cascade: pulumi.Input[Optional[_builtins.bool]] = None,
                 if_not_exists: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 owner: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Schema resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] database: The database name to alter schema
        :param pulumi.Input[_builtins.bool] drop_cascade: When true, will also drop all the objects that are contained in the schema
        :param pulumi.Input[_builtins.bool] if_not_exists: When true, use the existing schema if it exists
        :param pulumi.Input[_builtins.str] name: The name of the schema
        :param pulumi.Input[_builtins.str] owner: The ROLE name who owns the schema
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[SchemaArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Schema resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param SchemaArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SchemaArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 database: pulumi.Input[Optional[_builtins.str]] = None,
                 drop_cascade: pulumi.Input[Optional[_builtins.bool]] = None,
                 if_not_exists: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 owner: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SchemaArgs.__new__(SchemaArgs)

            __props__.__dict__["database"] = database
            __props__.__dict__["drop_cascade"] = drop_cascade
            __props__.__dict__["if_not_exists"] = if_not_exists
            __props__.__dict__["name"] = name
            __props__.__dict__["owner"] = owner
        super(Schema, __self__).__init__(
            'cockroachsql:index/schema:Schema',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            database: pulumi.Input[Optional[_builtins.str]] = None,
            drop_cascade: pulumi.Input[Optional[_builtins.bool]] = None,
            if_not_exists: pulumi.Input[Optional[_builtins.bool]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            owner: pulumi.Input[Optional[_builtins.str]] = None) -> 'Schema':
        """
        Get an existing Schema resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] database: The database name to alter schema
        :param pulumi.Input[_builtins.bool] drop_cascade: When true, will also drop all the objects that are contained in the schema
        :param pulumi.Input[_builtins.bool] if_not_exists: When true, use the existing schema if it exists
        :param pulumi.Input[_builtins.str] name: The name of the schema
        :param pulumi.Input[_builtins.str] owner: The ROLE name who owns the schema
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SchemaState.__new__(_SchemaState)

        __props__.__dict__["database"] = database
        __props__.__dict__["drop_cascade"] = drop_cascade
        __props__.__dict__["if_not_exists"] = if_not_exists
        __props__.__dict__["name"] = name
        __props__.__dict__["owner"] = owner
        return Schema(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def database(self) -> pulumi.Output[_builtins.str]:
        """
        The database name to alter schema
        """
        return pulumi.get(self, "database")

    @_builtins.property
    @pulumi.getter(name="dropCascade")
    def drop_cascade(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        When true, will also drop all the objects that are contained in the schema
        """
        return pulumi.get(self, "drop_cascade")

    @_builtins.property
    @pulumi.getter(name="ifNotExists")
    def if_not_exists(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        When true, use the existing schema if it exists
        """
        return pulumi.get(self, "if_not_exists")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the schema
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def owner(self) -> pulumi.Output[_builtins.str]:
        """
        The ROLE name who owns the schema
        """
        return pulumi.get(self, "owner")

