# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

clientcert: Optional[str]
"""
SSL client certificate if required by the database.
"""

connectTimeout: int
"""
Maximum wait for connection, in seconds. Zero or not specified means wait indefinitely.
"""

database: Optional[str]
"""
The name of the database to connect to (defaults to `defaultdb`).
"""

databaseUsername: Optional[str]
"""
Database username associated to the connected user (for user name maps)
"""

expectedVersion: Optional[str]
"""
Specify the expected version of CockroachDB.
"""

host: Optional[str]
"""
Name of CockroachDB server address to connect to
"""

maxConnections: Optional[int]
"""
Maximum number of connections to establish to the database. Zero means unlimited.
"""

password: Optional[str]
"""
Password to be used if the CockroachDB server demands password authentication
"""

port: Optional[int]
"""
The CockroachDB port number to connect to at the server host
"""

sslMode: Optional[str]

sslmode: Optional[str]
"""
This option determines whether or with what priority a secure SSL TCP/IP connection will be negotiated with the CockroachDB server
"""

sslrootcert: Optional[str]
"""
The SSL server root certificate file path. The file must contain PEM encoded data.
"""

superuser: Optional[bool]
"""
Specify if the user to connect as is a CockroachDB superuser or not.
"""

url: Optional[str]
"""
Connection URL for CockroachDB. If set, this overrides other connection parameters.
"""

username: Optional[str]
"""
CockroachDB user name to connect as
"""

