# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

import types

__config__ = pulumi.Config('cockroachsql')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def clientcert(self) -> Optional[str]:
        """
        SSL client certificate if required by the database.
        """
        return __config__.get('clientcert')

    @_builtins.property
    def connect_timeout(self) -> int:
        """
        Maximum wait for connection, in seconds. Zero or not specified means wait indefinitely.
        """
        return __config__.get_int('connectTimeout') or (_utilities.get_env_int('PGCONNECT_TIMEOUT') or 180)

    @_builtins.property
    def database(self) -> Optional[str]:
        """
        The name of the database to connect to (defaults to `defaultdb`).
        """
        return __config__.get('database')

    @_builtins.property
    def database_username(self) -> Optional[str]:
        """
        Database username associated to the connected user (for user name maps)
        """
        return __config__.get('databaseUsername')

    @_builtins.property
    def expected_version(self) -> Optional[str]:
        """
        Specify the expected version of CockroachDB.
        """
        return __config__.get('expectedVersion')

    @_builtins.property
    def host(self) -> Optional[str]:
        """
        Name of CockroachDB server address to connect to
        """
        return __config__.get('host')

    @_builtins.property
    def max_connections(self) -> Optional[int]:
        """
        Maximum number of connections to establish to the database. Zero means unlimited.
        """
        return __config__.get_int('maxConnections')

    @_builtins.property
    def password(self) -> Optional[str]:
        """
        Password to be used if the CockroachDB server demands password authentication
        """
        return __config__.get('password')

    @_builtins.property
    def port(self) -> Optional[int]:
        """
        The CockroachDB port number to connect to at the server host
        """
        return __config__.get_int('port')

    @_builtins.property
    def ssl_mode(self) -> Optional[str]:
        return __config__.get('sslMode')

    @_builtins.property
    def sslmode(self) -> Optional[str]:
        """
        This option determines whether or with what priority a secure SSL TCP/IP connection will be negotiated with the CockroachDB server
        """
        return __config__.get('sslmode') or _utilities.get_env('PGSSLMODE')

    @_builtins.property
    def sslrootcert(self) -> Optional[str]:
        """
        The SSL server root certificate file path. The file must contain PEM encoded data.
        """
        return __config__.get('sslrootcert')

    @_builtins.property
    def superuser(self) -> Optional[bool]:
        """
        Specify if the user to connect as is a CockroachDB superuser or not.
        """
        return __config__.get_bool('superuser')

    @_builtins.property
    def url(self) -> Optional[str]:
        """
        Connection URL for CockroachDB. If set, this overrides other connection parameters.
        """
        return __config__.get('url')

    @_builtins.property
    def username(self) -> Optional[str]:
        """
        CockroachDB user name to connect as
        """
        return __config__.get('username')

