// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cockroachsql

import (
	"context"
	"reflect"

	"github.com/nellisauction/pulumi-cockroachsql/sdk/go/cockroachsql/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetSchemas(ctx *pulumi.Context, args *GetSchemasArgs, opts ...pulumi.InvokeOption) (*GetSchemasResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetSchemasResult
	err := ctx.Invoke("cockroachsql:index/getSchemas:getSchemas", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSchemas.
type GetSchemasArgs struct {
	Database             string   `pulumi:"database"`
	IncludeSystemSchemas *bool    `pulumi:"includeSystemSchemas"`
	LikeAllPatterns      []string `pulumi:"likeAllPatterns"`
	LikeAnyPatterns      []string `pulumi:"likeAnyPatterns"`
	NotLikeAllPatterns   []string `pulumi:"notLikeAllPatterns"`
	RegexPattern         *string  `pulumi:"regexPattern"`
}

// A collection of values returned by getSchemas.
type GetSchemasResult struct {
	Database string `pulumi:"database"`
	// The provider-assigned unique ID for this managed resource.
	Id                   string   `pulumi:"id"`
	IncludeSystemSchemas *bool    `pulumi:"includeSystemSchemas"`
	LikeAllPatterns      []string `pulumi:"likeAllPatterns"`
	LikeAnyPatterns      []string `pulumi:"likeAnyPatterns"`
	NotLikeAllPatterns   []string `pulumi:"notLikeAllPatterns"`
	RegexPattern         *string  `pulumi:"regexPattern"`
	Schemas              []string `pulumi:"schemas"`
}

func GetSchemasOutput(ctx *pulumi.Context, args GetSchemasOutputArgs, opts ...pulumi.InvokeOption) GetSchemasResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetSchemasResultOutput, error) {
			args := v.(GetSchemasArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("cockroachsql:index/getSchemas:getSchemas", args, GetSchemasResultOutput{}, options).(GetSchemasResultOutput), nil
		}).(GetSchemasResultOutput)
}

// A collection of arguments for invoking getSchemas.
type GetSchemasOutputArgs struct {
	Database             pulumi.StringInput      `pulumi:"database"`
	IncludeSystemSchemas pulumi.BoolPtrInput     `pulumi:"includeSystemSchemas"`
	LikeAllPatterns      pulumi.StringArrayInput `pulumi:"likeAllPatterns"`
	LikeAnyPatterns      pulumi.StringArrayInput `pulumi:"likeAnyPatterns"`
	NotLikeAllPatterns   pulumi.StringArrayInput `pulumi:"notLikeAllPatterns"`
	RegexPattern         pulumi.StringPtrInput   `pulumi:"regexPattern"`
}

func (GetSchemasOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSchemasArgs)(nil)).Elem()
}

// A collection of values returned by getSchemas.
type GetSchemasResultOutput struct{ *pulumi.OutputState }

func (GetSchemasResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSchemasResult)(nil)).Elem()
}

func (o GetSchemasResultOutput) ToGetSchemasResultOutput() GetSchemasResultOutput {
	return o
}

func (o GetSchemasResultOutput) ToGetSchemasResultOutputWithContext(ctx context.Context) GetSchemasResultOutput {
	return o
}

func (o GetSchemasResultOutput) Database() pulumi.StringOutput {
	return o.ApplyT(func(v GetSchemasResult) string { return v.Database }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetSchemasResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetSchemasResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetSchemasResultOutput) IncludeSystemSchemas() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetSchemasResult) *bool { return v.IncludeSystemSchemas }).(pulumi.BoolPtrOutput)
}

func (o GetSchemasResultOutput) LikeAllPatterns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSchemasResult) []string { return v.LikeAllPatterns }).(pulumi.StringArrayOutput)
}

func (o GetSchemasResultOutput) LikeAnyPatterns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSchemasResult) []string { return v.LikeAnyPatterns }).(pulumi.StringArrayOutput)
}

func (o GetSchemasResultOutput) NotLikeAllPatterns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSchemasResult) []string { return v.NotLikeAllPatterns }).(pulumi.StringArrayOutput)
}

func (o GetSchemasResultOutput) RegexPattern() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetSchemasResult) *string { return v.RegexPattern }).(pulumi.StringPtrOutput)
}

func (o GetSchemasResultOutput) Schemas() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSchemasResult) []string { return v.Schemas }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetSchemasResultOutput{})
}
