// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cockroachsql

import (
	"context"
	"reflect"

	"github.com/nellisauction/pulumi-cockroachsql/sdk/go/cockroachsql/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetTables(ctx *pulumi.Context, args *GetTablesArgs, opts ...pulumi.InvokeOption) (*GetTablesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetTablesResult
	err := ctx.Invoke("cockroachsql:index/getTables:getTables", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTables.
type GetTablesArgs struct {
	Database           string   `pulumi:"database"`
	LikeAllPatterns    []string `pulumi:"likeAllPatterns"`
	LikeAnyPatterns    []string `pulumi:"likeAnyPatterns"`
	NotLikeAllPatterns []string `pulumi:"notLikeAllPatterns"`
	RegexPattern       *string  `pulumi:"regexPattern"`
	Schemas            []string `pulumi:"schemas"`
	TableTypes         []string `pulumi:"tableTypes"`
}

// A collection of values returned by getTables.
type GetTablesResult struct {
	Database string `pulumi:"database"`
	// The provider-assigned unique ID for this managed resource.
	Id                 string           `pulumi:"id"`
	LikeAllPatterns    []string         `pulumi:"likeAllPatterns"`
	LikeAnyPatterns    []string         `pulumi:"likeAnyPatterns"`
	NotLikeAllPatterns []string         `pulumi:"notLikeAllPatterns"`
	RegexPattern       *string          `pulumi:"regexPattern"`
	Schemas            []string         `pulumi:"schemas"`
	TableTypes         []string         `pulumi:"tableTypes"`
	Tables             []GetTablesTable `pulumi:"tables"`
}

func GetTablesOutput(ctx *pulumi.Context, args GetTablesOutputArgs, opts ...pulumi.InvokeOption) GetTablesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetTablesResultOutput, error) {
			args := v.(GetTablesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("cockroachsql:index/getTables:getTables", args, GetTablesResultOutput{}, options).(GetTablesResultOutput), nil
		}).(GetTablesResultOutput)
}

// A collection of arguments for invoking getTables.
type GetTablesOutputArgs struct {
	Database           pulumi.StringInput      `pulumi:"database"`
	LikeAllPatterns    pulumi.StringArrayInput `pulumi:"likeAllPatterns"`
	LikeAnyPatterns    pulumi.StringArrayInput `pulumi:"likeAnyPatterns"`
	NotLikeAllPatterns pulumi.StringArrayInput `pulumi:"notLikeAllPatterns"`
	RegexPattern       pulumi.StringPtrInput   `pulumi:"regexPattern"`
	Schemas            pulumi.StringArrayInput `pulumi:"schemas"`
	TableTypes         pulumi.StringArrayInput `pulumi:"tableTypes"`
}

func (GetTablesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTablesArgs)(nil)).Elem()
}

// A collection of values returned by getTables.
type GetTablesResultOutput struct{ *pulumi.OutputState }

func (GetTablesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTablesResult)(nil)).Elem()
}

func (o GetTablesResultOutput) ToGetTablesResultOutput() GetTablesResultOutput {
	return o
}

func (o GetTablesResultOutput) ToGetTablesResultOutputWithContext(ctx context.Context) GetTablesResultOutput {
	return o
}

func (o GetTablesResultOutput) Database() pulumi.StringOutput {
	return o.ApplyT(func(v GetTablesResult) string { return v.Database }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetTablesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTablesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetTablesResultOutput) LikeAllPatterns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetTablesResult) []string { return v.LikeAllPatterns }).(pulumi.StringArrayOutput)
}

func (o GetTablesResultOutput) LikeAnyPatterns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetTablesResult) []string { return v.LikeAnyPatterns }).(pulumi.StringArrayOutput)
}

func (o GetTablesResultOutput) NotLikeAllPatterns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetTablesResult) []string { return v.NotLikeAllPatterns }).(pulumi.StringArrayOutput)
}

func (o GetTablesResultOutput) RegexPattern() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetTablesResult) *string { return v.RegexPattern }).(pulumi.StringPtrOutput)
}

func (o GetTablesResultOutput) Schemas() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetTablesResult) []string { return v.Schemas }).(pulumi.StringArrayOutput)
}

func (o GetTablesResultOutput) TableTypes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetTablesResult) []string { return v.TableTypes }).(pulumi.StringArrayOutput)
}

func (o GetTablesResultOutput) Tables() GetTablesTableArrayOutput {
	return o.ApplyT(func(v GetTablesResult) []GetTablesTable { return v.Tables }).(GetTablesTableArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetTablesResultOutput{})
}
