// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cockroachsql

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/nellisauction/pulumi-cockroachsql/sdk/go/cockroachsql/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "cockroachsql:index/database:Database":
		r = &Database{}
	case "cockroachsql:index/defaultPrivileges:DefaultPrivileges":
		r = &DefaultPrivileges{}
	case "cockroachsql:index/grant:Grant":
		r = &Grant{}
	case "cockroachsql:index/grantRole:GrantRole":
		r = &GrantRole{}
	case "cockroachsql:index/role:Role":
		r = &Role{}
	case "cockroachsql:index/schema:Schema":
		r = &Schema{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:cockroachsql" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"cockroachsql",
		"index/database",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cockroachsql",
		"index/defaultPrivileges",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cockroachsql",
		"index/grant",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cockroachsql",
		"index/grantRole",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cockroachsql",
		"index/role",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"cockroachsql",
		"index/schema",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"cockroachsql",
		&pkg{version},
	)
}
