// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cockroachsql

import (
	"context"
	"reflect"

	"github.com/nellisauction/pulumi-cockroachsql/sdk/go/cockroachsql/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type ProviderClientcert struct {
	// The SSL client certificate file path. The file must contain PEM encoded data.
	Cert string `pulumi:"cert"`
	// The SSL client certificate private key file path. The file must contain PEM encoded data.
	Key string `pulumi:"key"`
	// Must be set to true if you are inlining the cert/key instead of using a file path.
	Sslinline *bool `pulumi:"sslinline"`
}

// ProviderClientcertInput is an input type that accepts ProviderClientcertArgs and ProviderClientcertOutput values.
// You can construct a concrete instance of `ProviderClientcertInput` via:
//
//	ProviderClientcertArgs{...}
type ProviderClientcertInput interface {
	pulumi.Input

	ToProviderClientcertOutput() ProviderClientcertOutput
	ToProviderClientcertOutputWithContext(context.Context) ProviderClientcertOutput
}

type ProviderClientcertArgs struct {
	// The SSL client certificate file path. The file must contain PEM encoded data.
	Cert pulumi.StringInput `pulumi:"cert"`
	// The SSL client certificate private key file path. The file must contain PEM encoded data.
	Key pulumi.StringInput `pulumi:"key"`
	// Must be set to true if you are inlining the cert/key instead of using a file path.
	Sslinline pulumi.BoolPtrInput `pulumi:"sslinline"`
}

func (ProviderClientcertArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderClientcert)(nil)).Elem()
}

func (i ProviderClientcertArgs) ToProviderClientcertOutput() ProviderClientcertOutput {
	return i.ToProviderClientcertOutputWithContext(context.Background())
}

func (i ProviderClientcertArgs) ToProviderClientcertOutputWithContext(ctx context.Context) ProviderClientcertOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderClientcertOutput)
}

func (i ProviderClientcertArgs) ToProviderClientcertPtrOutput() ProviderClientcertPtrOutput {
	return i.ToProviderClientcertPtrOutputWithContext(context.Background())
}

func (i ProviderClientcertArgs) ToProviderClientcertPtrOutputWithContext(ctx context.Context) ProviderClientcertPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderClientcertOutput).ToProviderClientcertPtrOutputWithContext(ctx)
}

// ProviderClientcertPtrInput is an input type that accepts ProviderClientcertArgs, ProviderClientcertPtr and ProviderClientcertPtrOutput values.
// You can construct a concrete instance of `ProviderClientcertPtrInput` via:
//
//	        ProviderClientcertArgs{...}
//
//	or:
//
//	        nil
type ProviderClientcertPtrInput interface {
	pulumi.Input

	ToProviderClientcertPtrOutput() ProviderClientcertPtrOutput
	ToProviderClientcertPtrOutputWithContext(context.Context) ProviderClientcertPtrOutput
}

type providerClientcertPtrType ProviderClientcertArgs

func ProviderClientcertPtr(v *ProviderClientcertArgs) ProviderClientcertPtrInput {
	return (*providerClientcertPtrType)(v)
}

func (*providerClientcertPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ProviderClientcert)(nil)).Elem()
}

func (i *providerClientcertPtrType) ToProviderClientcertPtrOutput() ProviderClientcertPtrOutput {
	return i.ToProviderClientcertPtrOutputWithContext(context.Background())
}

func (i *providerClientcertPtrType) ToProviderClientcertPtrOutputWithContext(ctx context.Context) ProviderClientcertPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderClientcertPtrOutput)
}

type ProviderClientcertOutput struct{ *pulumi.OutputState }

func (ProviderClientcertOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderClientcert)(nil)).Elem()
}

func (o ProviderClientcertOutput) ToProviderClientcertOutput() ProviderClientcertOutput {
	return o
}

func (o ProviderClientcertOutput) ToProviderClientcertOutputWithContext(ctx context.Context) ProviderClientcertOutput {
	return o
}

func (o ProviderClientcertOutput) ToProviderClientcertPtrOutput() ProviderClientcertPtrOutput {
	return o.ToProviderClientcertPtrOutputWithContext(context.Background())
}

func (o ProviderClientcertOutput) ToProviderClientcertPtrOutputWithContext(ctx context.Context) ProviderClientcertPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ProviderClientcert) *ProviderClientcert {
		return &v
	}).(ProviderClientcertPtrOutput)
}

// The SSL client certificate file path. The file must contain PEM encoded data.
func (o ProviderClientcertOutput) Cert() pulumi.StringOutput {
	return o.ApplyT(func(v ProviderClientcert) string { return v.Cert }).(pulumi.StringOutput)
}

// The SSL client certificate private key file path. The file must contain PEM encoded data.
func (o ProviderClientcertOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v ProviderClientcert) string { return v.Key }).(pulumi.StringOutput)
}

// Must be set to true if you are inlining the cert/key instead of using a file path.
func (o ProviderClientcertOutput) Sslinline() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ProviderClientcert) *bool { return v.Sslinline }).(pulumi.BoolPtrOutput)
}

type ProviderClientcertPtrOutput struct{ *pulumi.OutputState }

func (ProviderClientcertPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProviderClientcert)(nil)).Elem()
}

func (o ProviderClientcertPtrOutput) ToProviderClientcertPtrOutput() ProviderClientcertPtrOutput {
	return o
}

func (o ProviderClientcertPtrOutput) ToProviderClientcertPtrOutputWithContext(ctx context.Context) ProviderClientcertPtrOutput {
	return o
}

func (o ProviderClientcertPtrOutput) Elem() ProviderClientcertOutput {
	return o.ApplyT(func(v *ProviderClientcert) ProviderClientcert {
		if v != nil {
			return *v
		}
		var ret ProviderClientcert
		return ret
	}).(ProviderClientcertOutput)
}

// The SSL client certificate file path. The file must contain PEM encoded data.
func (o ProviderClientcertPtrOutput) Cert() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderClientcert) *string {
		if v == nil {
			return nil
		}
		return &v.Cert
	}).(pulumi.StringPtrOutput)
}

// The SSL client certificate private key file path. The file must contain PEM encoded data.
func (o ProviderClientcertPtrOutput) Key() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderClientcert) *string {
		if v == nil {
			return nil
		}
		return &v.Key
	}).(pulumi.StringPtrOutput)
}

// Must be set to true if you are inlining the cert/key instead of using a file path.
func (o ProviderClientcertPtrOutput) Sslinline() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ProviderClientcert) *bool {
		if v == nil {
			return nil
		}
		return v.Sslinline
	}).(pulumi.BoolPtrOutput)
}

type GetSequencesSequence struct {
	DataType   string `pulumi:"dataType"`
	ObjectName string `pulumi:"objectName"`
	SchemaName string `pulumi:"schemaName"`
}

// GetSequencesSequenceInput is an input type that accepts GetSequencesSequenceArgs and GetSequencesSequenceOutput values.
// You can construct a concrete instance of `GetSequencesSequenceInput` via:
//
//	GetSequencesSequenceArgs{...}
type GetSequencesSequenceInput interface {
	pulumi.Input

	ToGetSequencesSequenceOutput() GetSequencesSequenceOutput
	ToGetSequencesSequenceOutputWithContext(context.Context) GetSequencesSequenceOutput
}

type GetSequencesSequenceArgs struct {
	DataType   pulumi.StringInput `pulumi:"dataType"`
	ObjectName pulumi.StringInput `pulumi:"objectName"`
	SchemaName pulumi.StringInput `pulumi:"schemaName"`
}

func (GetSequencesSequenceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSequencesSequence)(nil)).Elem()
}

func (i GetSequencesSequenceArgs) ToGetSequencesSequenceOutput() GetSequencesSequenceOutput {
	return i.ToGetSequencesSequenceOutputWithContext(context.Background())
}

func (i GetSequencesSequenceArgs) ToGetSequencesSequenceOutputWithContext(ctx context.Context) GetSequencesSequenceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSequencesSequenceOutput)
}

// GetSequencesSequenceArrayInput is an input type that accepts GetSequencesSequenceArray and GetSequencesSequenceArrayOutput values.
// You can construct a concrete instance of `GetSequencesSequenceArrayInput` via:
//
//	GetSequencesSequenceArray{ GetSequencesSequenceArgs{...} }
type GetSequencesSequenceArrayInput interface {
	pulumi.Input

	ToGetSequencesSequenceArrayOutput() GetSequencesSequenceArrayOutput
	ToGetSequencesSequenceArrayOutputWithContext(context.Context) GetSequencesSequenceArrayOutput
}

type GetSequencesSequenceArray []GetSequencesSequenceInput

func (GetSequencesSequenceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetSequencesSequence)(nil)).Elem()
}

func (i GetSequencesSequenceArray) ToGetSequencesSequenceArrayOutput() GetSequencesSequenceArrayOutput {
	return i.ToGetSequencesSequenceArrayOutputWithContext(context.Background())
}

func (i GetSequencesSequenceArray) ToGetSequencesSequenceArrayOutputWithContext(ctx context.Context) GetSequencesSequenceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetSequencesSequenceArrayOutput)
}

type GetSequencesSequenceOutput struct{ *pulumi.OutputState }

func (GetSequencesSequenceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSequencesSequence)(nil)).Elem()
}

func (o GetSequencesSequenceOutput) ToGetSequencesSequenceOutput() GetSequencesSequenceOutput {
	return o
}

func (o GetSequencesSequenceOutput) ToGetSequencesSequenceOutputWithContext(ctx context.Context) GetSequencesSequenceOutput {
	return o
}

func (o GetSequencesSequenceOutput) DataType() pulumi.StringOutput {
	return o.ApplyT(func(v GetSequencesSequence) string { return v.DataType }).(pulumi.StringOutput)
}

func (o GetSequencesSequenceOutput) ObjectName() pulumi.StringOutput {
	return o.ApplyT(func(v GetSequencesSequence) string { return v.ObjectName }).(pulumi.StringOutput)
}

func (o GetSequencesSequenceOutput) SchemaName() pulumi.StringOutput {
	return o.ApplyT(func(v GetSequencesSequence) string { return v.SchemaName }).(pulumi.StringOutput)
}

type GetSequencesSequenceArrayOutput struct{ *pulumi.OutputState }

func (GetSequencesSequenceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetSequencesSequence)(nil)).Elem()
}

func (o GetSequencesSequenceArrayOutput) ToGetSequencesSequenceArrayOutput() GetSequencesSequenceArrayOutput {
	return o
}

func (o GetSequencesSequenceArrayOutput) ToGetSequencesSequenceArrayOutputWithContext(ctx context.Context) GetSequencesSequenceArrayOutput {
	return o
}

func (o GetSequencesSequenceArrayOutput) Index(i pulumi.IntInput) GetSequencesSequenceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetSequencesSequence {
		return vs[0].([]GetSequencesSequence)[vs[1].(int)]
	}).(GetSequencesSequenceOutput)
}

type GetTablesTable struct {
	ObjectName string `pulumi:"objectName"`
	SchemaName string `pulumi:"schemaName"`
	TableType  string `pulumi:"tableType"`
}

// GetTablesTableInput is an input type that accepts GetTablesTableArgs and GetTablesTableOutput values.
// You can construct a concrete instance of `GetTablesTableInput` via:
//
//	GetTablesTableArgs{...}
type GetTablesTableInput interface {
	pulumi.Input

	ToGetTablesTableOutput() GetTablesTableOutput
	ToGetTablesTableOutputWithContext(context.Context) GetTablesTableOutput
}

type GetTablesTableArgs struct {
	ObjectName pulumi.StringInput `pulumi:"objectName"`
	SchemaName pulumi.StringInput `pulumi:"schemaName"`
	TableType  pulumi.StringInput `pulumi:"tableType"`
}

func (GetTablesTableArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTablesTable)(nil)).Elem()
}

func (i GetTablesTableArgs) ToGetTablesTableOutput() GetTablesTableOutput {
	return i.ToGetTablesTableOutputWithContext(context.Background())
}

func (i GetTablesTableArgs) ToGetTablesTableOutputWithContext(ctx context.Context) GetTablesTableOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTablesTableOutput)
}

// GetTablesTableArrayInput is an input type that accepts GetTablesTableArray and GetTablesTableArrayOutput values.
// You can construct a concrete instance of `GetTablesTableArrayInput` via:
//
//	GetTablesTableArray{ GetTablesTableArgs{...} }
type GetTablesTableArrayInput interface {
	pulumi.Input

	ToGetTablesTableArrayOutput() GetTablesTableArrayOutput
	ToGetTablesTableArrayOutputWithContext(context.Context) GetTablesTableArrayOutput
}

type GetTablesTableArray []GetTablesTableInput

func (GetTablesTableArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTablesTable)(nil)).Elem()
}

func (i GetTablesTableArray) ToGetTablesTableArrayOutput() GetTablesTableArrayOutput {
	return i.ToGetTablesTableArrayOutputWithContext(context.Background())
}

func (i GetTablesTableArray) ToGetTablesTableArrayOutputWithContext(ctx context.Context) GetTablesTableArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTablesTableArrayOutput)
}

type GetTablesTableOutput struct{ *pulumi.OutputState }

func (GetTablesTableOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTablesTable)(nil)).Elem()
}

func (o GetTablesTableOutput) ToGetTablesTableOutput() GetTablesTableOutput {
	return o
}

func (o GetTablesTableOutput) ToGetTablesTableOutputWithContext(ctx context.Context) GetTablesTableOutput {
	return o
}

func (o GetTablesTableOutput) ObjectName() pulumi.StringOutput {
	return o.ApplyT(func(v GetTablesTable) string { return v.ObjectName }).(pulumi.StringOutput)
}

func (o GetTablesTableOutput) SchemaName() pulumi.StringOutput {
	return o.ApplyT(func(v GetTablesTable) string { return v.SchemaName }).(pulumi.StringOutput)
}

func (o GetTablesTableOutput) TableType() pulumi.StringOutput {
	return o.ApplyT(func(v GetTablesTable) string { return v.TableType }).(pulumi.StringOutput)
}

type GetTablesTableArrayOutput struct{ *pulumi.OutputState }

func (GetTablesTableArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTablesTable)(nil)).Elem()
}

func (o GetTablesTableArrayOutput) ToGetTablesTableArrayOutput() GetTablesTableArrayOutput {
	return o
}

func (o GetTablesTableArrayOutput) ToGetTablesTableArrayOutputWithContext(ctx context.Context) GetTablesTableArrayOutput {
	return o
}

func (o GetTablesTableArrayOutput) Index(i pulumi.IntInput) GetTablesTableOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetTablesTable {
		return vs[0].([]GetTablesTable)[vs[1].(int)]
	}).(GetTablesTableOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderClientcertInput)(nil)).Elem(), ProviderClientcertArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderClientcertPtrInput)(nil)).Elem(), ProviderClientcertArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetSequencesSequenceInput)(nil)).Elem(), GetSequencesSequenceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetSequencesSequenceArrayInput)(nil)).Elem(), GetSequencesSequenceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTablesTableInput)(nil)).Elem(), GetTablesTableArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTablesTableArrayInput)(nil)).Elem(), GetTablesTableArray{})
	pulumi.RegisterOutputType(ProviderClientcertOutput{})
	pulumi.RegisterOutputType(ProviderClientcertPtrOutput{})
	pulumi.RegisterOutputType(GetSequencesSequenceOutput{})
	pulumi.RegisterOutputType(GetSequencesSequenceArrayOutput{})
	pulumi.RegisterOutputType(GetTablesTableOutput{})
	pulumi.RegisterOutputType(GetTablesTableArrayOutput{})
}
