// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cockroachsql

import (
	"context"
	"reflect"

	"github.com/nellisauction/pulumi-cockroachsql/sdk/go/cockroachsql/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Role struct {
	pulumi.CustomResourceState

	// Determine whether this role will be permitted to create new roles
	CreateRole pulumi.BoolPtrOutput `pulumi:"createRole"`
	// Deprecated: Rename CockroachSQL role resource attribute "encrypted"
	Encrypted pulumi.StringPtrOutput `pulumi:"encrypted"`
	// Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
	IdleInTransactionSessionTimeout pulumi.IntPtrOutput `pulumi:"idleInTransactionSessionTimeout"`
	// Determine whether a role is allowed to log in
	Login pulumi.BoolPtrOutput `pulumi:"login"`
	// The name of the role
	Name pulumi.StringOutput `pulumi:"name"`
	// Sets the role's password
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Sets the role's password without storing it in the state file.
	PasswordWo pulumi.StringPtrOutput `pulumi:"passwordWo"`
	// Prevents applies from updating the role password on every apply unless the value changes.
	PasswordWoVersion pulumi.StringPtrOutput `pulumi:"passwordWoVersion"`
	// Role(s) to grant to this new role
	Roles pulumi.StringArrayOutput `pulumi:"roles"`
	// Sets the role's search path
	SearchPaths pulumi.StringArrayOutput `pulumi:"searchPaths"`
	// Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
	SkipDropRole pulumi.BoolPtrOutput `pulumi:"skipDropRole"`
	// Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
	SkipReassignOwned pulumi.BoolPtrOutput `pulumi:"skipReassignOwned"`
	// Abort any statement that takes more than the specified number of milliseconds
	StatementTimeout pulumi.IntPtrOutput `pulumi:"statementTimeout"`
	// Sets a date and time after which the role's password is no longer valid
	ValidUntil pulumi.StringPtrOutput `pulumi:"validUntil"`
}

// NewRole registers a new resource with the given unique name, arguments, and options.
func NewRole(ctx *pulumi.Context,
	name string, args *RoleArgs, opts ...pulumi.ResourceOption) (*Role, error) {
	if args == nil {
		args = &RoleArgs{}
	}

	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringPtrInput)
	}
	if args.PasswordWo != nil {
		args.PasswordWo = pulumi.ToSecret(args.PasswordWo).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
		"passwordWo",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Role
	err := ctx.RegisterResource("cockroachsql:index/role:Role", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRole gets an existing Role resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRole(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RoleState, opts ...pulumi.ResourceOption) (*Role, error) {
	var resource Role
	err := ctx.ReadResource("cockroachsql:index/role:Role", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Role resources.
type roleState struct {
	// Determine whether this role will be permitted to create new roles
	CreateRole *bool `pulumi:"createRole"`
	// Deprecated: Rename CockroachSQL role resource attribute "encrypted"
	Encrypted *string `pulumi:"encrypted"`
	// Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
	IdleInTransactionSessionTimeout *int `pulumi:"idleInTransactionSessionTimeout"`
	// Determine whether a role is allowed to log in
	Login *bool `pulumi:"login"`
	// The name of the role
	Name *string `pulumi:"name"`
	// Sets the role's password
	Password *string `pulumi:"password"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Sets the role's password without storing it in the state file.
	PasswordWo *string `pulumi:"passwordWo"`
	// Prevents applies from updating the role password on every apply unless the value changes.
	PasswordWoVersion *string `pulumi:"passwordWoVersion"`
	// Role(s) to grant to this new role
	Roles []string `pulumi:"roles"`
	// Sets the role's search path
	SearchPaths []string `pulumi:"searchPaths"`
	// Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
	SkipDropRole *bool `pulumi:"skipDropRole"`
	// Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
	SkipReassignOwned *bool `pulumi:"skipReassignOwned"`
	// Abort any statement that takes more than the specified number of milliseconds
	StatementTimeout *int `pulumi:"statementTimeout"`
	// Sets a date and time after which the role's password is no longer valid
	ValidUntil *string `pulumi:"validUntil"`
}

type RoleState struct {
	// Determine whether this role will be permitted to create new roles
	CreateRole pulumi.BoolPtrInput
	// Deprecated: Rename CockroachSQL role resource attribute "encrypted"
	Encrypted pulumi.StringPtrInput
	// Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
	IdleInTransactionSessionTimeout pulumi.IntPtrInput
	// Determine whether a role is allowed to log in
	Login pulumi.BoolPtrInput
	// The name of the role
	Name pulumi.StringPtrInput
	// Sets the role's password
	Password pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Sets the role's password without storing it in the state file.
	PasswordWo pulumi.StringPtrInput
	// Prevents applies from updating the role password on every apply unless the value changes.
	PasswordWoVersion pulumi.StringPtrInput
	// Role(s) to grant to this new role
	Roles pulumi.StringArrayInput
	// Sets the role's search path
	SearchPaths pulumi.StringArrayInput
	// Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
	SkipDropRole pulumi.BoolPtrInput
	// Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
	SkipReassignOwned pulumi.BoolPtrInput
	// Abort any statement that takes more than the specified number of milliseconds
	StatementTimeout pulumi.IntPtrInput
	// Sets a date and time after which the role's password is no longer valid
	ValidUntil pulumi.StringPtrInput
}

func (RoleState) ElementType() reflect.Type {
	return reflect.TypeOf((*roleState)(nil)).Elem()
}

type roleArgs struct {
	// Determine whether this role will be permitted to create new roles
	CreateRole *bool `pulumi:"createRole"`
	// Deprecated: Rename CockroachSQL role resource attribute "encrypted"
	Encrypted *string `pulumi:"encrypted"`
	// Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
	IdleInTransactionSessionTimeout *int `pulumi:"idleInTransactionSessionTimeout"`
	// Determine whether a role is allowed to log in
	Login *bool `pulumi:"login"`
	// The name of the role
	Name *string `pulumi:"name"`
	// Sets the role's password
	Password *string `pulumi:"password"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Sets the role's password without storing it in the state file.
	PasswordWo *string `pulumi:"passwordWo"`
	// Prevents applies from updating the role password on every apply unless the value changes.
	PasswordWoVersion *string `pulumi:"passwordWoVersion"`
	// Role(s) to grant to this new role
	Roles []string `pulumi:"roles"`
	// Sets the role's search path
	SearchPaths []string `pulumi:"searchPaths"`
	// Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
	SkipDropRole *bool `pulumi:"skipDropRole"`
	// Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
	SkipReassignOwned *bool `pulumi:"skipReassignOwned"`
	// Abort any statement that takes more than the specified number of milliseconds
	StatementTimeout *int `pulumi:"statementTimeout"`
	// Sets a date and time after which the role's password is no longer valid
	ValidUntil *string `pulumi:"validUntil"`
}

// The set of arguments for constructing a Role resource.
type RoleArgs struct {
	// Determine whether this role will be permitted to create new roles
	CreateRole pulumi.BoolPtrInput
	// Deprecated: Rename CockroachSQL role resource attribute "encrypted"
	Encrypted pulumi.StringPtrInput
	// Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
	IdleInTransactionSessionTimeout pulumi.IntPtrInput
	// Determine whether a role is allowed to log in
	Login pulumi.BoolPtrInput
	// The name of the role
	Name pulumi.StringPtrInput
	// Sets the role's password
	Password pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Sets the role's password without storing it in the state file.
	PasswordWo pulumi.StringPtrInput
	// Prevents applies from updating the role password on every apply unless the value changes.
	PasswordWoVersion pulumi.StringPtrInput
	// Role(s) to grant to this new role
	Roles pulumi.StringArrayInput
	// Sets the role's search path
	SearchPaths pulumi.StringArrayInput
	// Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
	SkipDropRole pulumi.BoolPtrInput
	// Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
	SkipReassignOwned pulumi.BoolPtrInput
	// Abort any statement that takes more than the specified number of milliseconds
	StatementTimeout pulumi.IntPtrInput
	// Sets a date and time after which the role's password is no longer valid
	ValidUntil pulumi.StringPtrInput
}

func (RoleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*roleArgs)(nil)).Elem()
}

type RoleInput interface {
	pulumi.Input

	ToRoleOutput() RoleOutput
	ToRoleOutputWithContext(ctx context.Context) RoleOutput
}

func (*Role) ElementType() reflect.Type {
	return reflect.TypeOf((**Role)(nil)).Elem()
}

func (i *Role) ToRoleOutput() RoleOutput {
	return i.ToRoleOutputWithContext(context.Background())
}

func (i *Role) ToRoleOutputWithContext(ctx context.Context) RoleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RoleOutput)
}

// RoleArrayInput is an input type that accepts RoleArray and RoleArrayOutput values.
// You can construct a concrete instance of `RoleArrayInput` via:
//
//	RoleArray{ RoleArgs{...} }
type RoleArrayInput interface {
	pulumi.Input

	ToRoleArrayOutput() RoleArrayOutput
	ToRoleArrayOutputWithContext(context.Context) RoleArrayOutput
}

type RoleArray []RoleInput

func (RoleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Role)(nil)).Elem()
}

func (i RoleArray) ToRoleArrayOutput() RoleArrayOutput {
	return i.ToRoleArrayOutputWithContext(context.Background())
}

func (i RoleArray) ToRoleArrayOutputWithContext(ctx context.Context) RoleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RoleArrayOutput)
}

// RoleMapInput is an input type that accepts RoleMap and RoleMapOutput values.
// You can construct a concrete instance of `RoleMapInput` via:
//
//	RoleMap{ "key": RoleArgs{...} }
type RoleMapInput interface {
	pulumi.Input

	ToRoleMapOutput() RoleMapOutput
	ToRoleMapOutputWithContext(context.Context) RoleMapOutput
}

type RoleMap map[string]RoleInput

func (RoleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Role)(nil)).Elem()
}

func (i RoleMap) ToRoleMapOutput() RoleMapOutput {
	return i.ToRoleMapOutputWithContext(context.Background())
}

func (i RoleMap) ToRoleMapOutputWithContext(ctx context.Context) RoleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RoleMapOutput)
}

type RoleOutput struct{ *pulumi.OutputState }

func (RoleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Role)(nil)).Elem()
}

func (o RoleOutput) ToRoleOutput() RoleOutput {
	return o
}

func (o RoleOutput) ToRoleOutputWithContext(ctx context.Context) RoleOutput {
	return o
}

// Determine whether this role will be permitted to create new roles
func (o RoleOutput) CreateRole() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Role) pulumi.BoolPtrOutput { return v.CreateRole }).(pulumi.BoolPtrOutput)
}

// Deprecated: Rename CockroachSQL role resource attribute "encrypted"
func (o RoleOutput) Encrypted() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Role) pulumi.StringPtrOutput { return v.Encrypted }).(pulumi.StringPtrOutput)
}

// Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
func (o RoleOutput) IdleInTransactionSessionTimeout() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Role) pulumi.IntPtrOutput { return v.IdleInTransactionSessionTimeout }).(pulumi.IntPtrOutput)
}

// Determine whether a role is allowed to log in
func (o RoleOutput) Login() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Role) pulumi.BoolPtrOutput { return v.Login }).(pulumi.BoolPtrOutput)
}

// The name of the role
func (o RoleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Role) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Sets the role's password
func (o RoleOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Role) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
// Sets the role's password without storing it in the state file.
func (o RoleOutput) PasswordWo() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Role) pulumi.StringPtrOutput { return v.PasswordWo }).(pulumi.StringPtrOutput)
}

// Prevents applies from updating the role password on every apply unless the value changes.
func (o RoleOutput) PasswordWoVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Role) pulumi.StringPtrOutput { return v.PasswordWoVersion }).(pulumi.StringPtrOutput)
}

// Role(s) to grant to this new role
func (o RoleOutput) Roles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Role) pulumi.StringArrayOutput { return v.Roles }).(pulumi.StringArrayOutput)
}

// Sets the role's search path
func (o RoleOutput) SearchPaths() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Role) pulumi.StringArrayOutput { return v.SearchPaths }).(pulumi.StringArrayOutput)
}

// Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
func (o RoleOutput) SkipDropRole() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Role) pulumi.BoolPtrOutput { return v.SkipDropRole }).(pulumi.BoolPtrOutput)
}

// Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
func (o RoleOutput) SkipReassignOwned() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Role) pulumi.BoolPtrOutput { return v.SkipReassignOwned }).(pulumi.BoolPtrOutput)
}

// Abort any statement that takes more than the specified number of milliseconds
func (o RoleOutput) StatementTimeout() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Role) pulumi.IntPtrOutput { return v.StatementTimeout }).(pulumi.IntPtrOutput)
}

// Sets a date and time after which the role's password is no longer valid
func (o RoleOutput) ValidUntil() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Role) pulumi.StringPtrOutput { return v.ValidUntil }).(pulumi.StringPtrOutput)
}

type RoleArrayOutput struct{ *pulumi.OutputState }

func (RoleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Role)(nil)).Elem()
}

func (o RoleArrayOutput) ToRoleArrayOutput() RoleArrayOutput {
	return o
}

func (o RoleArrayOutput) ToRoleArrayOutputWithContext(ctx context.Context) RoleArrayOutput {
	return o
}

func (o RoleArrayOutput) Index(i pulumi.IntInput) RoleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Role {
		return vs[0].([]*Role)[vs[1].(int)]
	}).(RoleOutput)
}

type RoleMapOutput struct{ *pulumi.OutputState }

func (RoleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Role)(nil)).Elem()
}

func (o RoleMapOutput) ToRoleMapOutput() RoleMapOutput {
	return o
}

func (o RoleMapOutput) ToRoleMapOutputWithContext(ctx context.Context) RoleMapOutput {
	return o
}

func (o RoleMapOutput) MapIndex(k pulumi.StringInput) RoleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Role {
		return vs[0].(map[string]*Role)[vs[1].(string)]
	}).(RoleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RoleInput)(nil)).Elem(), &Role{})
	pulumi.RegisterInputType(reflect.TypeOf((*RoleArrayInput)(nil)).Elem(), RoleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RoleMapInput)(nil)).Elem(), RoleMap{})
	pulumi.RegisterOutputType(RoleOutput{})
	pulumi.RegisterOutputType(RoleArrayOutput{})
	pulumi.RegisterOutputType(RoleMapOutput{})
}
