// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetSequencesSequence {
    dataType: string;
    objectName: string;
    schemaName: string;
}

export interface GetTablesTable {
    objectName: string;
    schemaName: string;
    tableType: string;
}

export namespace config {
    export interface Clientcert {
        /**
         * The SSL client certificate file path. The file must contain PEM encoded data.
         */
        cert: string;
        /**
         * The SSL client certificate private key file path. The file must contain PEM encoded data.
         */
        key: string;
        /**
         * Must be set to true if you are inlining the cert/key instead of using a file path.
         */
        sslinline?: boolean;
    }

}
