name: "Build SDK"
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build_sdk:
    name: build_sdk
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [dotnet, go, nodejs, python]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          cache_save: false

      - name: Setup Go Cache
        if: matrix.language == 'go'
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: |
            provider/*.sum
            sdk/go/*.sum
            *.sum

      - name: Prepare local workspace
        run: make prepare_local_workspace

      - name: Download prerequisites
        uses: ./.github/actions/download-prerequisites

      - name: Build SDK
        run: make build_${{ matrix.language }}

      - name: Upload SDK
        uses: ./.github/actions/upload-sdk
        with:
          language: ${{ matrix.language }}
