name: main
on:
  workflow_dispatch: {}
  push:
    branches:
    - main

jobs:
  prerequisites:
    uses: .github/workflows/prerequisites.yml
    with:
      default_branch: main
      is_pr: false
      is_automated: false
    secrets: inherit
