name: "Main Pipeline"
on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths-ignore:
    - "**.md"

jobs:
  prerequisites:
    uses: ./.github/workflows/prerequisites.yml
    with:
      default_branch: main
      is_pr: false
      is_automated: false
    secrets: inherit

  build_provider:
    needs: prerequisites
    uses: ./.github/workflows/build_provider.yml
    with:
      version: ${{ needs.prerequisites.outputs.version }}
    secrets: inherit

  build_sdk:
    needs: prerequisites
    uses: ./.github/workflows/build_sdk.yml
    with:
      version: ${{ needs.prerequisites.outputs.version }}
    secrets: inherit

  test:
    needs: [prerequisites, build_provider, build_sdk]
    uses: ./.github/workflows/test.yml
    with:
      version: ${{ needs.prerequisites.outputs.version }}
    secrets: inherit
