name: Prerequisites
on:
  workflow_call:
    inputs:
      is_pr:
        type: boolean
        required: true
      is_automated:
        type: boolean
        required: true
      default_branch:
        type: string
        required: true
    outputs:
      version:
        value: ${{ jobs.prerequisites.outputs.version }}

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    outputs:
      version: ${{ steps.provider-version.outputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - uses: pulumi/provider-version-action@v1
        id: provider-version
        with:
          major-version: 1
          set-env: 'PROVIDER_VERSION'

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          cache_save: true

      - name: Setup Go Cache
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: |
            provider/*.sum
            sdk/go/*.sum
            *.sum

      - name: Prepare local workspace
        run: make prepare_local_workspace

      - name: Generate schema
        run: make schema

      - name: Build provider binary
        run: make provider

      - name: Unit-test provider code
        run: make test_provider
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: ./.github/actions/upload-prerequisites
