name: Prerequisites
on:
  workflow_call:
    inputs:
      is_pr:
        type: boolean
        required: true
      is_automated:
        type: boolean
        required: true
      default_branch:
        type: string
        required: true
    outputs:
      version:
        value: "0.1.0"

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dummy Prerequisites"
