name: Release
on:
  push:
    tags:
      - v*.*.*

env:
  PULUMI_API: https://api.pulumi.com
  TF_APPEND_USER_AGENT: pulumi
  MISE_PYTHON_GITHUB_ATTESTATIONS: "false"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Set Version
        run: echo "PROVIDER_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Install Mise
        run: |
          curl https://mise.jdx.dev/install.sh | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH

      - name: Build and Package Provider
        run: |
          (cd provider && go mod tidy)
          make tfgen_build_only
          ./bin/pulumi-tfgen-cockroachsql schema --out provider/cmd/pulumi-resource-cockroachsql
          
          # Cross compile and Package for common platforms
          make provider_dist-linux-amd64
          make provider_dist-linux-arm64
          make provider_dist-darwin-amd64
          make provider_dist-darwin-arm64
          make provider_dist-windows-amd64

      - name: Build and Pack SDKs
        run: |
          make build_nodejs
          make build_python
          make build_dotnet

      - name: GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes \
            bin/*.tar.gz

      - name: Authenticate with Cloudsmith
        uses: cloudsmith-io/cloudsmith-cli-action@v2
        with:
          oidc-namespace: 'nellisauction'
          oidc-service-slug: 'github-actions'

      - name: Push to Cloudsmith
        run: |
          # Node.js
          cloudsmith push npm nellisauction/pulumi-cockroachsql sdk/nodejs/bin/*.tgz
          
          # Python
          cloudsmith push python nellisauction/pulumi-cockroachsql sdk/python/bin/dist/*.whl
          cloudsmith push python nellisauction/pulumi-cockroachsql sdk/python/bin/dist/*.tar.gz
          
          # NuGet (Dotnet)
          cloudsmith push nuget nellisauction/pulumi-cockroachsql sdk/dotnet/bin/*.nupkg
