name: release
on:
  push:
    tags:
    - v*.*.*

env:
  PULUMI_API: https://api.pulumi.com
  TF_APPEND_USER_AGENT: pulumi
  PROVIDER_VERSION: ${{ github.ref_name }}

jobs:
  build_provider:
    name: build_provider
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - {os: linux, arch: amd64}
          - {os: linux, arch: arm64}
          - {os: darwin, arch: amd64}
          - {os: darwin, arch: arm64}
          - {os: windows, arch: amd64}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Build provider
        run: |
          make prepare_local_workspace
          make schema
          make provider-${{ matrix.platform.os }}-${{ matrix.platform.arch }}
          make provider_dist-${{ matrix.platform.os }}-${{ matrix.platform.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: provider-${{ matrix.platform.os }}-${{ matrix.platform.arch }}
          path: bin/pulumi-resource-cockroachsql-v${{ github.ref_name }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}.tar.gz

  build_sdk:
    name: build_sdk
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [nodejs, python, dotnet, go]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Build SDK
        run: |
          make prepare_local_workspace
          make schema
          make build_${{ matrix.language }}

      - name: Upload SDK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.language }}-sdk
          path: sdk/${{ matrix.language }}

  publish:
    needs: [build_provider, build_sdk]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GH Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          generate_release_notes: true
          files: artifacts/provider-*/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with Cloudsmith
        uses: cloudsmith-io/cloudsmith-cli-action@v2
        with:
          oidc-namespace: 'nellisauction'
          oidc-service-slug: 'github-actions'

      - name: Push Node.js SDK
        run: |
          cd artifacts/nodejs-sdk/bin
          cloudsmith push npm nellisauction/pulumi-cockroachsql *.tgz

      - name: Push Python SDK
        run: |
          cd artifacts/python-sdk/bin/dist
          cloudsmith push python nellisauction/pulumi-cockroachsql *.whl
          cloudsmith push python nellisauction/pulumi-cockroachsql *.tar.gz

      - name: Push Dotnet SDK
        run: |
          cd artifacts/dotnet-sdk/bin
          cloudsmith push nuget nellisauction/pulumi-cockroachsql *.nupkg
