name: release
on:
  push:
    tags:
    - v*.*.*

jobs:
  prerequisites:
    uses: ./.github/workflows/prerequisites.yml
    with:
      default_branch: main
      is_pr: false
      is_automated: false
    secrets: inherit

  build_provider:
    needs: prerequisites
    uses: ./.github/workflows/build_provider.yml
    with:
      version: ${{ needs.prerequisites.outputs.version }}
    secrets: inherit

  build_sdk:
    needs: prerequisites
    uses: ./.github/workflows/build_sdk.yml
    with:
      version: ${{ needs.prerequisites.outputs.version }}
    secrets: inherit

  publish:
    needs: [prerequisites, build_provider, build_sdk]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Create dist directory
        run: mkdir -p dist

      - name: Download provider assets
        uses: actions/download-artifact@v4
        with:
          pattern: pulumi-resource-cockroachsql-v${{ needs.prerequisites.outputs.version }}-*
          path: dist
          merge-multiple: true

      - name: Calculate checksums
        working-directory: dist
        run: shasum ./*.tar.gz > "pulumi-cockroachsql_${{ needs.prerequisites.outputs.version }}_checksums.txt"

      - name: Create GH Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          generate_release_notes: true
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with Cloudsmith
        uses: cloudsmith-io/cloudsmith-cli-action@v2
        with:
          oidc-namespace: 'nellisauction'
          oidc-service-slug: 'github-actions'

      - name: Download SDKs
        uses: actions/download-artifact@v4
        with:
          pattern: "*-sdk.tar.gz"
          path: sdks-tar
          merge-multiple: true

      - name: Push SDKs to Cloudsmith
        run: |
          for f in sdks-tar/*.tar.gz; do
            lang=$(basename $f -sdk.tar.gz)
            mkdir -p "pkg-$lang"
            tar -xzf "$f" -C "pkg-$lang"
            
            if [ "$lang" == "nodejs" ]; then
              cloudsmith push npm nellisauction/pulumi-cockroachsql "pkg-$lang/bin/"*.tgz
            elif [ "$lang" == "python" ]; then
              cloudsmith push python nellisauction/pulumi-cockroachsql "pkg-$lang/bin/dist/"*.whl
              cloudsmith push python nellisauction/pulumi-cockroachsql "pkg-$lang/bin/dist/"*.tar.gz
            elif [ "$lang" == "dotnet" ]; then
              cloudsmith push nuget nellisauction/pulumi-cockroachsql "pkg-$lang/bin/"*.nupkg
            fi
          done
