on:
  workflow_call:
    inputs:
      is_pr:
        type: boolean
        required: true
      is_automated:
        type: boolean
        required: true
      default_branch:
        type: string
        required: true
    outputs:
      version:
        value: ${{ jobs.prerequisites.outputs.version }}

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - id: set_version
        run: echo "version=0.1.0" >> "$GITHUB_OUTPUT"
