on:
  workflow_call:
    inputs:
      is_pr:
        type: boolean
        required: true
      is_automated:
        type: boolean
        required: true
      default_branch:
        type: string
        required: true
    outputs:
      version:
        value: ${{ jobs.prerequisites.outputs.version }}

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    outputs:
      version: ${{ steps.provider-version.outputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - env:
          ESC_ACTION_ENVIRONMENT: imports/github-secrets
          ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: "false"
          ESC_ACTION_OIDC_AUTH: "true"
          ESC_ACTION_OIDC_ORGANIZATION: nellisauction
          ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - uses: actions/create-github-app-token@v1
        id: app-auth
        with:
          app-id: ${{ steps.esc-secrets.outputs.PULUMI_PROVIDER_AUTOMATION_APP_ID }}
          private-key: ${{ steps.esc-secrets.outputs.PULUMI_PROVIDER_AUTOMATION_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: pulumi/provider-version-action@v1
        id: provider-version
        with:
          major-version: 1
          set-env: 'PROVIDER_VERSION'
