// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Database extends pulumi.CustomResource {
    /**
     * Get an existing Database resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DatabaseState, opts?: pulumi.CustomResourceOptions): Database {
        return new Database(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroachsql:index/database:Database';

    /**
     * Returns true if the given object is an instance of Database.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Database {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Database.__pulumiType;
    }

    /**
     * Character set encoding to use in the new database
     */
    declare public readonly encoding: pulumi.Output<string>;
    /**
     * Collation order (LC_COLLATE) to use in the new database
     */
    declare public readonly lcCollate: pulumi.Output<string>;
    /**
     * Character classification (LC_CTYPE) to use in the new database
     */
    declare public readonly lcCtype: pulumi.Output<string>;
    /**
     * The name of the database
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The role name of the database owner
     */
    declare public readonly owner: pulumi.Output<string>;
    /**
     * The name of the tablespace that will be associated with the new database
     */
    declare public readonly tablespaceName: pulumi.Output<string>;
    /**
     * The name of the template database from which to create the new database
     */
    declare public readonly template: pulumi.Output<string>;

    /**
     * Create a Database resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: DatabaseArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DatabaseArgs | DatabaseState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DatabaseState | undefined;
            resourceInputs["encoding"] = state?.encoding;
            resourceInputs["lcCollate"] = state?.lcCollate;
            resourceInputs["lcCtype"] = state?.lcCtype;
            resourceInputs["name"] = state?.name;
            resourceInputs["owner"] = state?.owner;
            resourceInputs["tablespaceName"] = state?.tablespaceName;
            resourceInputs["template"] = state?.template;
        } else {
            const args = argsOrState as DatabaseArgs | undefined;
            resourceInputs["encoding"] = args?.encoding;
            resourceInputs["lcCollate"] = args?.lcCollate;
            resourceInputs["lcCtype"] = args?.lcCtype;
            resourceInputs["name"] = args?.name;
            resourceInputs["owner"] = args?.owner;
            resourceInputs["tablespaceName"] = args?.tablespaceName;
            resourceInputs["template"] = args?.template;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Database.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Database resources.
 */
export interface DatabaseState {
    /**
     * Character set encoding to use in the new database
     */
    encoding?: pulumi.Input<string | undefined>;
    /**
     * Collation order (LC_COLLATE) to use in the new database
     */
    lcCollate?: pulumi.Input<string | undefined>;
    /**
     * Character classification (LC_CTYPE) to use in the new database
     */
    lcCtype?: pulumi.Input<string | undefined>;
    /**
     * The name of the database
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The role name of the database owner
     */
    owner?: pulumi.Input<string | undefined>;
    /**
     * The name of the tablespace that will be associated with the new database
     */
    tablespaceName?: pulumi.Input<string | undefined>;
    /**
     * The name of the template database from which to create the new database
     */
    template?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Database resource.
 */
export interface DatabaseArgs {
    /**
     * Character set encoding to use in the new database
     */
    encoding?: pulumi.Input<string | undefined>;
    /**
     * Collation order (LC_COLLATE) to use in the new database
     */
    lcCollate?: pulumi.Input<string | undefined>;
    /**
     * Character classification (LC_CTYPE) to use in the new database
     */
    lcCtype?: pulumi.Input<string | undefined>;
    /**
     * The name of the database
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The role name of the database owner
     */
    owner?: pulumi.Input<string | undefined>;
    /**
     * The name of the tablespace that will be associated with the new database
     */
    tablespaceName?: pulumi.Input<string | undefined>;
    /**
     * The name of the template database from which to create the new database
     */
    template?: pulumi.Input<string | undefined>;
}
