// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSchemas(args: GetSchemasArgs, opts?: pulumi.InvokeOptions): Promise<GetSchemasResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cockroachsql:index/getSchemas:getSchemas", {
        "database": args.database,
        "includeSystemSchemas": args.includeSystemSchemas,
        "likeAllPatterns": args.likeAllPatterns,
        "likeAnyPatterns": args.likeAnyPatterns,
        "notLikeAllPatterns": args.notLikeAllPatterns,
        "regexPattern": args.regexPattern,
    }, opts);
}

/**
 * A collection of arguments for invoking getSchemas.
 */
export interface GetSchemasArgs {
    database: string;
    includeSystemSchemas?: boolean;
    likeAllPatterns?: string[];
    likeAnyPatterns?: string[];
    notLikeAllPatterns?: string[];
    regexPattern?: string;
}

/**
 * A collection of values returned by getSchemas.
 */
export interface GetSchemasResult {
    readonly database: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly includeSystemSchemas?: boolean;
    readonly likeAllPatterns?: string[];
    readonly likeAnyPatterns?: string[];
    readonly notLikeAllPatterns?: string[];
    readonly regexPattern?: string;
    readonly schemas: string[];
}
export function getSchemasOutput(args: GetSchemasOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSchemasResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cockroachsql:index/getSchemas:getSchemas", {
        "database": args.database,
        "includeSystemSchemas": args.includeSystemSchemas,
        "likeAllPatterns": args.likeAllPatterns,
        "likeAnyPatterns": args.likeAnyPatterns,
        "notLikeAllPatterns": args.notLikeAllPatterns,
        "regexPattern": args.regexPattern,
    }, opts);
}

/**
 * A collection of arguments for invoking getSchemas.
 */
export interface GetSchemasOutputArgs {
    database: pulumi.Input<string>;
    includeSystemSchemas?: pulumi.Input<boolean | undefined>;
    likeAllPatterns?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    likeAnyPatterns?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    notLikeAllPatterns?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    regexPattern?: pulumi.Input<string | undefined>;
}
