// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Role extends pulumi.CustomResource {
    /**
     * Get an existing Role resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RoleState, opts?: pulumi.CustomResourceOptions): Role {
        return new Role(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cockroachsql:index/role:Role';

    /**
     * Returns true if the given object is an instance of Role.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Role {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Role.__pulumiType;
    }

    /**
     * Determine whether this role will be permitted to create new roles
     */
    declare public readonly createRole: pulumi.Output<boolean | undefined>;
    /**
     * @deprecated Rename CockroachSQL role resource attribute "encrypted"
     */
    declare public readonly encrypted: pulumi.Output<string | undefined>;
    /**
     * Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
     */
    declare public readonly idleInTransactionSessionTimeout: pulumi.Output<number | undefined>;
    /**
     * Determine whether a role is allowed to log in
     */
    declare public readonly login: pulumi.Output<boolean | undefined>;
    /**
     * The name of the role
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Sets the role's password
     */
    declare public readonly password: pulumi.Output<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Sets the role's password without storing it in the state file.
     */
    declare public readonly passwordWo: pulumi.Output<string | undefined>;
    /**
     * Prevents applies from updating the role password on every apply unless the value changes.
     */
    declare public readonly passwordWoVersion: pulumi.Output<string | undefined>;
    /**
     * Role(s) to grant to this new role
     */
    declare public readonly roles: pulumi.Output<string[] | undefined>;
    /**
     * Sets the role's search path
     */
    declare public readonly searchPaths: pulumi.Output<string[] | undefined>;
    /**
     * Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
     */
    declare public readonly skipDropRole: pulumi.Output<boolean | undefined>;
    /**
     * Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
     */
    declare public readonly skipReassignOwned: pulumi.Output<boolean | undefined>;
    /**
     * Abort any statement that takes more than the specified number of milliseconds
     */
    declare public readonly statementTimeout: pulumi.Output<number | undefined>;
    /**
     * Sets a date and time after which the role's password is no longer valid
     */
    declare public readonly validUntil: pulumi.Output<string | undefined>;

    /**
     * Create a Role resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: RoleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RoleArgs | RoleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RoleState | undefined;
            resourceInputs["createRole"] = state?.createRole;
            resourceInputs["encrypted"] = state?.encrypted;
            resourceInputs["idleInTransactionSessionTimeout"] = state?.idleInTransactionSessionTimeout;
            resourceInputs["login"] = state?.login;
            resourceInputs["name"] = state?.name;
            resourceInputs["password"] = state?.password;
            resourceInputs["passwordWo"] = state?.passwordWo;
            resourceInputs["passwordWoVersion"] = state?.passwordWoVersion;
            resourceInputs["roles"] = state?.roles;
            resourceInputs["searchPaths"] = state?.searchPaths;
            resourceInputs["skipDropRole"] = state?.skipDropRole;
            resourceInputs["skipReassignOwned"] = state?.skipReassignOwned;
            resourceInputs["statementTimeout"] = state?.statementTimeout;
            resourceInputs["validUntil"] = state?.validUntil;
        } else {
            const args = argsOrState as RoleArgs | undefined;
            resourceInputs["createRole"] = args?.createRole;
            resourceInputs["encrypted"] = args?.encrypted;
            resourceInputs["idleInTransactionSessionTimeout"] = args?.idleInTransactionSessionTimeout;
            resourceInputs["login"] = args?.login;
            resourceInputs["name"] = args?.name;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["passwordWo"] = args?.passwordWo ? pulumi.secret(args.passwordWo) : undefined;
            resourceInputs["passwordWoVersion"] = args?.passwordWoVersion;
            resourceInputs["roles"] = args?.roles;
            resourceInputs["searchPaths"] = args?.searchPaths;
            resourceInputs["skipDropRole"] = args?.skipDropRole;
            resourceInputs["skipReassignOwned"] = args?.skipReassignOwned;
            resourceInputs["statementTimeout"] = args?.statementTimeout;
            resourceInputs["validUntil"] = args?.validUntil;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password", "passwordWo"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Role.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Role resources.
 */
export interface RoleState {
    /**
     * Determine whether this role will be permitted to create new roles
     */
    createRole?: pulumi.Input<boolean | undefined>;
    /**
     * @deprecated Rename CockroachSQL role resource attribute "encrypted"
     */
    encrypted?: pulumi.Input<string | undefined>;
    /**
     * Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
     */
    idleInTransactionSessionTimeout?: pulumi.Input<number | undefined>;
    /**
     * Determine whether a role is allowed to log in
     */
    login?: pulumi.Input<boolean | undefined>;
    /**
     * The name of the role
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Sets the role's password
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Sets the role's password without storing it in the state file.
     */
    passwordWo?: pulumi.Input<string | undefined>;
    /**
     * Prevents applies from updating the role password on every apply unless the value changes.
     */
    passwordWoVersion?: pulumi.Input<string | undefined>;
    /**
     * Role(s) to grant to this new role
     */
    roles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Sets the role's search path
     */
    searchPaths?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
     */
    skipDropRole?: pulumi.Input<boolean | undefined>;
    /**
     * Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
     */
    skipReassignOwned?: pulumi.Input<boolean | undefined>;
    /**
     * Abort any statement that takes more than the specified number of milliseconds
     */
    statementTimeout?: pulumi.Input<number | undefined>;
    /**
     * Sets a date and time after which the role's password is no longer valid
     */
    validUntil?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Role resource.
 */
export interface RoleArgs {
    /**
     * Determine whether this role will be permitted to create new roles
     */
    createRole?: pulumi.Input<boolean | undefined>;
    /**
     * @deprecated Rename CockroachSQL role resource attribute "encrypted"
     */
    encrypted?: pulumi.Input<string | undefined>;
    /**
     * Terminate any session with an open transaction that has been idle for longer than the specified duration in milliseconds
     */
    idleInTransactionSessionTimeout?: pulumi.Input<number | undefined>;
    /**
     * Determine whether a role is allowed to log in
     */
    login?: pulumi.Input<boolean | undefined>;
    /**
     * The name of the role
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Sets the role's password
     */
    password?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Sets the role's password without storing it in the state file.
     */
    passwordWo?: pulumi.Input<string | undefined>;
    /**
     * Prevents applies from updating the role password on every apply unless the value changes.
     */
    passwordWoVersion?: pulumi.Input<string | undefined>;
    /**
     * Role(s) to grant to this new role
     */
    roles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Sets the role's search path
     */
    searchPaths?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Skip actually running the DROP ROLE command when removing a ROLE from CockroachSQL
     */
    skipDropRole?: pulumi.Input<boolean | undefined>;
    /**
     * Skip actually running the REASSIGN OWNED command when removing a role from CockroachSQL
     */
    skipReassignOwned?: pulumi.Input<boolean | undefined>;
    /**
     * Abort any statement that takes more than the specified number of milliseconds
     */
    statementTimeout?: pulumi.Input<number | undefined>;
    /**
     * Sets a date and time after which the role's password is no longer valid
     */
    validUntil?: pulumi.Input<string | undefined>;
}
